// Banco de dados de alimentos: Tabela Brasileira de Composição de Alimentos (TACO),
// 4ª edição, NEPA/UNICAMP. Valores nutricionais por 100g (ou 100ml para líquidos).
// Fonte dos dados: https://github.com/brolesi/taco (dados públicos, NEPA/UNICAMP)
const BANCO_ALIMENTOS = [
  { nome: "Arroz, integral, cozido", categoria: "Cereais e derivados", kcal: 124, proteina: 2.6, carboidrato: 25.8, gordura: 1 },
  { nome: "Arroz, integral, cru", categoria: "Cereais e derivados", kcal: 360, proteina: 7.3, carboidrato: 77.5, gordura: 1.9 },
  { nome: "Arroz, tipo 1, cozido", categoria: "Cereais e derivados", kcal: 128, proteina: 2.5, carboidrato: 28.1, gordura: 0.2 },
  { nome: "Arroz, tipo 1, cru", categoria: "Cereais e derivados", kcal: 358, proteina: 7.2, carboidrato: 78.8, gordura: 0.3 },
  { nome: "Arroz, tipo 2, cozido", categoria: "Cereais e derivados", kcal: 130, proteina: 2.6, carboidrato: 28.2, gordura: 0.4 },
  { nome: "Arroz, tipo 2, cru", categoria: "Cereais e derivados", kcal: 358, proteina: 7.2, carboidrato: 78.9, gordura: 0.3 },
  { nome: "Aveia, flocos, crua", categoria: "Cereais e derivados", kcal: 394, proteina: 13.9, carboidrato: 66.6, gordura: 8.5 },
  { nome: "Biscoito, doce, maisena", categoria: "Cereais e derivados", kcal: 443, proteina: 8.1, carboidrato: 75.2, gordura: 12 },
  { nome: "Biscoito, doce, recheado com chocolate", categoria: "Cereais e derivados", kcal: 472, proteina: 6.4, carboidrato: 70.5, gordura: 19.6 },
  { nome: "Biscoito, doce, recheado com morango", categoria: "Cereais e derivados", kcal: 471, proteina: 5.7, carboidrato: 71, gordura: 19.6 },
  { nome: "Biscoito, doce, wafer, recheado de chocolate", categoria: "Cereais e derivados", kcal: 502, proteina: 5.6, carboidrato: 67.5, gordura: 24.7 },
  { nome: "Biscoito, doce, wafer, recheado de morango", categoria: "Cereais e derivados", kcal: 513, proteina: 4.5, carboidrato: 67.4, gordura: 26.4 },
  { nome: "Biscoito, salgado, cream cracker", categoria: "Cereais e derivados", kcal: 432, proteina: 10.1, carboidrato: 68.7, gordura: 14.4 },
  { nome: "Bolo, mistura para", categoria: "Cereais e derivados", kcal: 419, proteina: 6.2, carboidrato: 84.7, gordura: 6.1 },
  { nome: "Bolo, pronto, aipim", categoria: "Cereais e derivados", kcal: 324, proteina: 4.4, carboidrato: 47.9, gordura: 12.7 },
  { nome: "Bolo, pronto, chocolate", categoria: "Cereais e derivados", kcal: 410, proteina: 6.2, carboidrato: 54.7, gordura: 18.5 },
  { nome: "Bolo, pronto, coco", categoria: "Cereais e derivados", kcal: 333, proteina: 5.7, carboidrato: 52.3, gordura: 11.3 },
  { nome: "Bolo, pronto, milho", categoria: "Cereais e derivados", kcal: 311, proteina: 4.8, carboidrato: 45.1, gordura: 12.4 },
  { nome: "Canjica, branca, crua", categoria: "Cereais e derivados", kcal: 358, proteina: 7.2, carboidrato: 78.1, gordura: 1 },
  { nome: "Canjica, com leite integral", categoria: "Cereais e derivados", kcal: 112, proteina: 2.4, carboidrato: 23.6, gordura: 1.2 },
  { nome: "Cereais, milho, flocos, com sal", categoria: "Cereais e derivados", kcal: 370, proteina: 7.3, carboidrato: 80.8, gordura: 1.6 },
  { nome: "Cereais, milho, flocos, sem sal", categoria: "Cereais e derivados", kcal: 363, proteina: 6.9, carboidrato: 80.4, gordura: 1.2 },
  { nome: "Cereais, mingau, milho, infantil", categoria: "Cereais e derivados", kcal: 394, proteina: 6.4, carboidrato: 87.3, gordura: 1.1 },
  { nome: "Cereais, mistura para vitamina, trigo, cevada e aveia", categoria: "Cereais e derivados", kcal: 381, proteina: 8.9, carboidrato: 81.6, gordura: 2.1 },
  { nome: "Cereal matinal, milho", categoria: "Cereais e derivados", kcal: 365, proteina: 7.2, carboidrato: 83.8, gordura: 1 },
  { nome: "Cereal matinal, milho, açúcar", categoria: "Cereais e derivados", kcal: 377, proteina: 4.7, carboidrato: 88.8, gordura: 0.7 },
  { nome: "Creme de arroz, pó", categoria: "Cereais e derivados", kcal: 386, proteina: 7, carboidrato: 83.9, gordura: 1.2 },
  { nome: "Creme de milho, pó", categoria: "Cereais e derivados", kcal: 333, proteina: 4.8, carboidrato: 86.1, gordura: 1.6 },
  { nome: "Curau, milho verde", categoria: "Cereais e derivados", kcal: 78, proteina: 2.4, carboidrato: 13.9, gordura: 1.6 },
  { nome: "Curau, milho verde, mistura para", categoria: "Cereais e derivados", kcal: 402, proteina: 2.2, carboidrato: 79.8, gordura: 13.4 },
  { nome: "Farinha, de arroz, enriquecida", categoria: "Cereais e derivados", kcal: 363, proteina: 1.3, carboidrato: 85.5, gordura: 0.3 },
  { nome: "Farinha, de centeio, integral", categoria: "Cereais e derivados", kcal: 336, proteina: 12.5, carboidrato: 73.3, gordura: 1.8 },
  { nome: "Farinha, de milho, amarela", categoria: "Cereais e derivados", kcal: 351, proteina: 7.2, carboidrato: 79.1, gordura: 1.5 },
  { nome: "Farinha, de rosca", categoria: "Cereais e derivados", kcal: 371, proteina: 11.4, carboidrato: 75.8, gordura: 1.5 },
  { nome: "Farinha, de trigo", categoria: "Cereais e derivados", kcal: 360, proteina: 9.8, carboidrato: 75.1, gordura: 1.4 },
  { nome: "Farinha, láctea, de cereais", categoria: "Cereais e derivados", kcal: 415, proteina: 11.9, carboidrato: 77.8, gordura: 5.8 },
  { nome: "Lasanha, massa fresca, cozida", categoria: "Cereais e derivados", kcal: 164, proteina: 5.8, carboidrato: 32.5, gordura: 1.2 },
  { nome: "Lasanha, massa fresca, crua", categoria: "Cereais e derivados", kcal: 220, proteina: 7, carboidrato: 45.1, gordura: 1.3 },
  { nome: "Macarrão, instantâneo", categoria: "Cereais e derivados", kcal: 436, proteina: 8.8, carboidrato: 62.4, gordura: 17.2 },
  { nome: "Macarrão, trigo, cru", categoria: "Cereais e derivados", kcal: 371, proteina: 10, carboidrato: 77.9, gordura: 1.3 },
  { nome: "Macarrão, trigo, cru, com ovos", categoria: "Cereais e derivados", kcal: 371, proteina: 10.3, carboidrato: 76.6, gordura: 2 },
  { nome: "Milho, amido, cru", categoria: "Cereais e derivados", kcal: 361, proteina: 0.6, carboidrato: 87.1, gordura: 0 },
  { nome: "Milho, fubá, cru", categoria: "Cereais e derivados", kcal: 353, proteina: 7.2, carboidrato: 78.9, gordura: 1.9 },
  { nome: "Milho, verde, cru", categoria: "Cereais e derivados", kcal: 138, proteina: 6.6, carboidrato: 28.6, gordura: 0.6 },
  { nome: "Milho, verde, enlatado, drenado", categoria: "Cereais e derivados", kcal: 98, proteina: 3.2, carboidrato: 17.1, gordura: 2.4 },
  { nome: "Mingau tradicional, pó", categoria: "Cereais e derivados", kcal: 373, proteina: 0.6, carboidrato: 89.3, gordura: 0.4 },
  { nome: "Pamonha, barra para cozimento, pré-cozida", categoria: "Cereais e derivados", kcal: 171, proteina: 2.6, carboidrato: 30.7, gordura: 4.8 },
  { nome: "Pão, aveia, forma", categoria: "Cereais e derivados", kcal: 343, proteina: 12.4, carboidrato: 59.6, gordura: 5.7 },
  { nome: "Pão, de soja", categoria: "Cereais e derivados", kcal: 309, proteina: 11.3, carboidrato: 56.5, gordura: 3.6 },
  { nome: "Pão, glúten, forma", categoria: "Cereais e derivados", kcal: 253, proteina: 12, carboidrato: 44.1, gordura: 2.7 },
  { nome: "Pão, milho, forma", categoria: "Cereais e derivados", kcal: 292, proteina: 8.3, carboidrato: 56.4, gordura: 3.1 },
  { nome: "Pão, trigo, forma, integral", categoria: "Cereais e derivados", kcal: 253, proteina: 9.4, carboidrato: 49.9, gordura: 3.7 },
  { nome: "Pão, trigo, francês", categoria: "Cereais e derivados", kcal: 300, proteina: 8, carboidrato: 58.6, gordura: 3.1 },
  { nome: "Pão, trigo, sovado", categoria: "Cereais e derivados", kcal: 311, proteina: 8.4, carboidrato: 61.5, gordura: 2.8 },
  { nome: "Pastel, de carne, cru", categoria: "Cereais e derivados", kcal: 289, proteina: 10.7, carboidrato: 42, gordura: 8.8 },
  { nome: "Pastel, de carne, frito", categoria: "Cereais e derivados", kcal: 388, proteina: 10.1, carboidrato: 43.8, gordura: 20.1 },
  { nome: "Pastel, de queijo, cru", categoria: "Cereais e derivados", kcal: 308, proteina: 9.9, carboidrato: 45.9, gordura: 9.6 },
  { nome: "Pastel, de queijo, frito", categoria: "Cereais e derivados", kcal: 422, proteina: 8.7, carboidrato: 48.1, gordura: 22.7 },
  { nome: "Pastel, massa, crua", categoria: "Cereais e derivados", kcal: 310, proteina: 6.9, carboidrato: 57.4, gordura: 5.5 },
  { nome: "Pastel, massa, frita", categoria: "Cereais e derivados", kcal: 570, proteina: 6, carboidrato: 49.3, gordura: 40.9 },
  { nome: "Pipoca, com óleo de soja, sem sal", categoria: "Cereais e derivados", kcal: 448, proteina: 9.9, carboidrato: 70.3, gordura: 15.9 },
  { nome: "Polenta, pré-cozida", categoria: "Cereais e derivados", kcal: 103, proteina: 2.3, carboidrato: 23.3, gordura: 0.3 },
  { nome: "Torrada, pão francês", categoria: "Cereais e derivados", kcal: 377, proteina: 10.5, carboidrato: 74.6, gordura: 3.3 },
  { nome: "Abóbora, cabotian, cozida", categoria: "Verduras, hortaliças e derivados", kcal: 48, proteina: 1.4, carboidrato: 10.8, gordura: 0.7 },
  { nome: "Abóbora, cabotian, crua", categoria: "Verduras, hortaliças e derivados", kcal: 39, proteina: 1.7, carboidrato: 8.4, gordura: 0.5 },
  { nome: "Abóbora, menina brasileira, crua", categoria: "Verduras, hortaliças e derivados", kcal: 14, proteina: 0.6, carboidrato: 3.3, gordura: 0 },
  { nome: "Abóbora, moranga, crua", categoria: "Verduras, hortaliças e derivados", kcal: 12, proteina: 1, carboidrato: 2.7, gordura: 0.1 },
  { nome: "Abóbora, moranga, refogada", categoria: "Verduras, hortaliças e derivados", kcal: 29, proteina: 0.4, carboidrato: 6, gordura: 0.8 },
  { nome: "Abóbora, pescoço, crua", categoria: "Verduras, hortaliças e derivados", kcal: 24, proteina: 0.7, carboidrato: 6.1, gordura: 0.1 },
  { nome: "Abobrinha, italiana, cozida", categoria: "Verduras, hortaliças e derivados", kcal: 15, proteina: 1.1, carboidrato: 3, gordura: 0.2 },
  { nome: "Abobrinha, italiana, crua", categoria: "Verduras, hortaliças e derivados", kcal: 19, proteina: 1.1, carboidrato: 4.3, gordura: 0.1 },
  { nome: "Abobrinha, italiana, refogada", categoria: "Verduras, hortaliças e derivados", kcal: 24, proteina: 1.1, carboidrato: 4.2, gordura: 0.8 },
  { nome: "Abobrinha, paulista, crua", categoria: "Verduras, hortaliças e derivados", kcal: 31, proteina: 0.6, carboidrato: 7.9, gordura: 0.1 },
  { nome: "Acelga, crua", categoria: "Verduras, hortaliças e derivados", kcal: 21, proteina: 1.4, carboidrato: 4.6, gordura: 0.1 },
  { nome: "Agrião, cru", categoria: "Verduras, hortaliças e derivados", kcal: 17, proteina: 2.7, carboidrato: 2.3, gordura: 0.2 },
  { nome: "Aipo, cru", categoria: "Verduras, hortaliças e derivados", kcal: 19, proteina: 0.8, carboidrato: 4.3, gordura: 0.1 },
  { nome: "Alface, americana, crua", categoria: "Verduras, hortaliças e derivados", kcal: 9, proteina: 0.6, carboidrato: 1.7, gordura: 0.1 },
  { nome: "Alface, crespa, crua", categoria: "Verduras, hortaliças e derivados", kcal: 11, proteina: 1.3, carboidrato: 1.7, gordura: 0.2 },
  { nome: "Alface, lisa, crua", categoria: "Verduras, hortaliças e derivados", kcal: 14, proteina: 1.7, carboidrato: 2.4, gordura: 0.1 },
  { nome: "Alface, roxa, crua", categoria: "Verduras, hortaliças e derivados", kcal: 13, proteina: 0.9, carboidrato: 2.5, gordura: 0.2 },
  { nome: "Alfavaca, crua", categoria: "Verduras, hortaliças e derivados", kcal: 29, proteina: 2.7, carboidrato: 5.2, gordura: 0.5 },
  { nome: "Alho, cru", categoria: "Verduras, hortaliças e derivados", kcal: 113, proteina: 7, carboidrato: 23.9, gordura: 0.2 },
  { nome: "Alho-poró, cru", categoria: "Verduras, hortaliças e derivados", kcal: 32, proteina: 1.4, carboidrato: 6.9, gordura: 0.1 },
  { nome: "Almeirão, cru", categoria: "Verduras, hortaliças e derivados", kcal: 18, proteina: 1.8, carboidrato: 3.3, gordura: 0.2 },
  { nome: "Almeirão, refogado", categoria: "Verduras, hortaliças e derivados", kcal: 65, proteina: 1.7, carboidrato: 5.7, gordura: 4.8 },
  { nome: "Batata, baroa, cozida", categoria: "Verduras, hortaliças e derivados", kcal: 80, proteina: 0.9, carboidrato: 18.9, gordura: 0.2 },
  { nome: "Batata, baroa, crua", categoria: "Verduras, hortaliças e derivados", kcal: 101, proteina: 1, carboidrato: 24, gordura: 0.2 },
  { nome: "Batata, doce, cozida", categoria: "Verduras, hortaliças e derivados", kcal: 77, proteina: 0.6, carboidrato: 18.4, gordura: 0.1 },
  { nome: "Batata, doce, crua", categoria: "Verduras, hortaliças e derivados", kcal: 118, proteina: 1.3, carboidrato: 28.2, gordura: 0.1 },
  { nome: "Batata, frita, tipo chips, industrializada", categoria: "Verduras, hortaliças e derivados", kcal: 543, proteina: 5.6, carboidrato: 51.2, gordura: 36.6 },
  { nome: "Batata, inglesa, cozida", categoria: "Verduras, hortaliças e derivados", kcal: 52, proteina: 1.2, carboidrato: 11.9, gordura: 0 },
  { nome: "Batata, inglesa, crua", categoria: "Verduras, hortaliças e derivados", kcal: 64, proteina: 1.8, carboidrato: 14.7, gordura: 0 },
  { nome: "Batata, inglesa, frita", categoria: "Verduras, hortaliças e derivados", kcal: 267, proteina: 5, carboidrato: 35.6, gordura: 13.1 },
  { nome: "Batata, inglesa, sauté", categoria: "Verduras, hortaliças e derivados", kcal: 68, proteina: 1.3, carboidrato: 14.1, gordura: 0.9 },
  { nome: "Berinjela, cozida", categoria: "Verduras, hortaliças e derivados", kcal: 19, proteina: 0.7, carboidrato: 4.5, gordura: 0.1 },
  { nome: "Berinjela, crua", categoria: "Verduras, hortaliças e derivados", kcal: 20, proteina: 1.2, carboidrato: 4.4, gordura: 0.1 },
  { nome: "Beterraba, cozida", categoria: "Verduras, hortaliças e derivados", kcal: 32, proteina: 1.3, carboidrato: 7.2, gordura: 0.1 },
  { nome: "Beterraba, crua", categoria: "Verduras, hortaliças e derivados", kcal: 49, proteina: 1.9, carboidrato: 11.1, gordura: 0.1 },
  { nome: "Biscoito, polvilho doce", categoria: "Verduras, hortaliças e derivados", kcal: 438, proteina: 1.3, carboidrato: 80.5, gordura: 12.2 },
  { nome: "Brócolis, cozido", categoria: "Verduras, hortaliças e derivados", kcal: 25, proteina: 2.1, carboidrato: 4.4, gordura: 0.5 },
  { nome: "Brócolis, cru", categoria: "Verduras, hortaliças e derivados", kcal: 25, proteina: 3.6, carboidrato: 4, gordura: 0.3 },
  { nome: "Cará, cozido", categoria: "Verduras, hortaliças e derivados", kcal: 78, proteina: 1.5, carboidrato: 18.9, gordura: 0.1 },
  { nome: "Cará, cru", categoria: "Verduras, hortaliças e derivados", kcal: 96, proteina: 2.3, carboidrato: 23, gordura: 0.1 },
  { nome: "Caruru, cru", categoria: "Verduras, hortaliças e derivados", kcal: 34, proteina: 3.2, carboidrato: 6, gordura: 0.6 },
  { nome: "Catalonha, crua", categoria: "Verduras, hortaliças e derivados", kcal: 24, proteina: 1.9, carboidrato: 4.8, gordura: 0.3 },
  { nome: "Catalonha, refogada", categoria: "Verduras, hortaliças e derivados", kcal: 63, proteina: 2, carboidrato: 4.8, gordura: 4.8 },
  { nome: "Cebola, crua", categoria: "Verduras, hortaliças e derivados", kcal: 39, proteina: 1.7, carboidrato: 8.9, gordura: 0.1 },
  { nome: "Cebolinha, crua", categoria: "Verduras, hortaliças e derivados", kcal: 20, proteina: 1.9, carboidrato: 3.4, gordura: 0.4 },
  { nome: "Cenoura, cozida", categoria: "Verduras, hortaliças e derivados", kcal: 30, proteina: 0.8, carboidrato: 6.7, gordura: 0.2 },
  { nome: "Cenoura, crua", categoria: "Verduras, hortaliças e derivados", kcal: 34, proteina: 1.3, carboidrato: 7.7, gordura: 0.2 },
  { nome: "Chicória, crua", categoria: "Verduras, hortaliças e derivados", kcal: 14, proteina: 1.1, carboidrato: 2.9, gordura: 0.1 },
  { nome: "Chuchu, cozido", categoria: "Verduras, hortaliças e derivados", kcal: 19, proteina: 0.4, carboidrato: 4.8, gordura: 0 },
  { nome: "Chuchu, cru", categoria: "Verduras, hortaliças e derivados", kcal: 17, proteina: 0.7, carboidrato: 4.1, gordura: 0.1 },
  { nome: "Coentro, folhas desidratadas", categoria: "Verduras, hortaliças e derivados", kcal: 309, proteina: 20.9, carboidrato: 48, gordura: 10.4 },
  { nome: "Couve, manteiga, crua", categoria: "Verduras, hortaliças e derivados", kcal: 27, proteina: 2.9, carboidrato: 4.3, gordura: 0.5 },
  { nome: "Couve, manteiga, refogada", categoria: "Verduras, hortaliças e derivados", kcal: 90, proteina: 1.7, carboidrato: 8.7, gordura: 6.6 },
  { nome: "Couve-flor, crua", categoria: "Verduras, hortaliças e derivados", kcal: 23, proteina: 1.9, carboidrato: 4.5, gordura: 0.2 },
  { nome: "Couve-flor, cozida", categoria: "Verduras, hortaliças e derivados", kcal: 19, proteina: 1.2, carboidrato: 3.9, gordura: 0.3 },
  { nome: "Espinafre, Nova Zelândia, cru", categoria: "Verduras, hortaliças e derivados", kcal: 16, proteina: 2, carboidrato: 2.6, gordura: 0.2 },
  { nome: "Espinafre, Nova Zelândia, refogado", categoria: "Verduras, hortaliças e derivados", kcal: 67, proteina: 2.7, carboidrato: 4.2, gordura: 5.4 },
  { nome: "Farinha, de mandioca, crua", categoria: "Verduras, hortaliças e derivados", kcal: 361, proteina: 1.6, carboidrato: 87.9, gordura: 0.3 },
  { nome: "Farinha, de mandioca, torrada", categoria: "Verduras, hortaliças e derivados", kcal: 365, proteina: 1.2, carboidrato: 89.2, gordura: 0.3 },
  { nome: "Farinha, de puba", categoria: "Verduras, hortaliças e derivados", kcal: 360, proteina: 1.6, carboidrato: 87.3, gordura: 0.5 },
  { nome: "Fécula, de mandioca", categoria: "Verduras, hortaliças e derivados", kcal: 331, proteina: 0.5, carboidrato: 81.1, gordura: 0.3 },
  { nome: "Feijão, broto, cru", categoria: "Verduras, hortaliças e derivados", kcal: 39, proteina: 4.2, carboidrato: 7.8, gordura: 0.1 },
  { nome: "Inhame, cru", categoria: "Verduras, hortaliças e derivados", kcal: 97, proteina: 2.1, carboidrato: 23.2, gordura: 0.2 },
  { nome: "Jiló, cru", categoria: "Verduras, hortaliças e derivados", kcal: 27, proteina: 1.4, carboidrato: 6.2, gordura: 0.2 },
  { nome: "Jurubeba, crua", categoria: "Verduras, hortaliças e derivados", kcal: 126, proteina: 4.4, carboidrato: 23.1, gordura: 3.9 },
  { nome: "Mandioca, cozida", categoria: "Verduras, hortaliças e derivados", kcal: 125, proteina: 0.6, carboidrato: 30.1, gordura: 0.3 },
  { nome: "Mandioca, crua", categoria: "Verduras, hortaliças e derivados", kcal: 151, proteina: 1.1, carboidrato: 36.2, gordura: 0.3 },
  { nome: "Mandioca, farofa, temperada", categoria: "Verduras, hortaliças e derivados", kcal: 406, proteina: 2.1, carboidrato: 80.3, gordura: 9.1 },
  { nome: "Mandioca, frita", categoria: "Verduras, hortaliças e derivados", kcal: 300, proteina: 1.4, carboidrato: 50.3, gordura: 11.2 },
  { nome: "Manjericão, cru", categoria: "Verduras, hortaliças e derivados", kcal: 21, proteina: 2, carboidrato: 3.6, gordura: 0.4 },
  { nome: "Maxixe, cru", categoria: "Verduras, hortaliças e derivados", kcal: 14, proteina: 1.4, carboidrato: 2.7, gordura: 0.1 },
  { nome: "Mostarda, folha, crua", categoria: "Verduras, hortaliças e derivados", kcal: 18, proteina: 2.1, carboidrato: 3.2, gordura: 0.2 },
  { nome: "Nhoque, batata, cozido", categoria: "Verduras, hortaliças e derivados", kcal: 181, proteina: 5.9, carboidrato: 36.8, gordura: 1.9 },
  { nome: "Nabo, cru", categoria: "Verduras, hortaliças e derivados", kcal: 18, proteina: 1.2, carboidrato: 4.1, gordura: 0.1 },
  { nome: "Palmito, juçara, em conserva", categoria: "Verduras, hortaliças e derivados", kcal: 23, proteina: 1.8, carboidrato: 4.3, gordura: 0.4 },
  { nome: "Palmito, pupunha, em conserva", categoria: "Verduras, hortaliças e derivados", kcal: 29, proteina: 2.5, carboidrato: 5.5, gordura: 0.5 },
  { nome: "Pão, de queijo, assado", categoria: "Verduras, hortaliças e derivados", kcal: 363, proteina: 5.1, carboidrato: 34.2, gordura: 24.6 },
  { nome: "Pão, de queijo, cru", categoria: "Verduras, hortaliças e derivados", kcal: 295, proteina: 3.6, carboidrato: 38.5, gordura: 14 },
  { nome: "Pepino, cru", categoria: "Verduras, hortaliças e derivados", kcal: 10, proteina: 0.9, carboidrato: 2, gordura: 0 },
  { nome: "Pimentão, amarelo, cru", categoria: "Verduras, hortaliças e derivados", kcal: 28, proteina: 1.2, carboidrato: 6, gordura: 0.4 },
  { nome: "Pimentão, verde, cru", categoria: "Verduras, hortaliças e derivados", kcal: 21, proteina: 1.1, carboidrato: 4.9, gordura: 0.2 },
  { nome: "Pimentão, vermelho, cru", categoria: "Verduras, hortaliças e derivados", kcal: 23, proteina: 1, carboidrato: 5.5, gordura: 0.1 },
  { nome: "Polvilho, doce", categoria: "Verduras, hortaliças e derivados", kcal: 351, proteina: 0.4, carboidrato: 86.8, gordura: 0 },
  { nome: "Quiabo, cru", categoria: "Verduras, hortaliças e derivados", kcal: 30, proteina: 1.9, carboidrato: 6.4, gordura: 0.3 },
  { nome: "Rabanete, cru", categoria: "Verduras, hortaliças e derivados", kcal: 14, proteina: 1.4, carboidrato: 2.7, gordura: 0.1 },
  { nome: "Repolho, branco, cru", categoria: "Verduras, hortaliças e derivados", kcal: 17, proteina: 0.9, carboidrato: 3.9, gordura: 0.1 },
  { nome: "Repolho, roxo, cru", categoria: "Verduras, hortaliças e derivados", kcal: 31, proteina: 1.9, carboidrato: 7.2, gordura: 0.1 },
  { nome: "Repolho, roxo, refogado", categoria: "Verduras, hortaliças e derivados", kcal: 42, proteina: 1.8, carboidrato: 7.6, gordura: 1.2 },
  { nome: "Rúcula, crua", categoria: "Verduras, hortaliças e derivados", kcal: 13, proteina: 1.8, carboidrato: 2.2, gordura: 0.1 },
  { nome: "Salsa, crua", categoria: "Verduras, hortaliças e derivados", kcal: 33, proteina: 3.3, carboidrato: 5.7, gordura: 0.6 },
  { nome: "Seleta de legumes, enlatada", categoria: "Verduras, hortaliças e derivados", kcal: 57, proteina: 3.4, carboidrato: 12.7, gordura: 0.4 },
  { nome: "Serralha, crua", categoria: "Verduras, hortaliças e derivados", kcal: 30, proteina: 2.7, carboidrato: 4.9, gordura: 0.7 },
  { nome: "Taioba, crua", categoria: "Verduras, hortaliças e derivados", kcal: 34, proteina: 2.9, carboidrato: 5.4, gordura: 0.9 },
  { nome: "Tomate, com semente, cru", categoria: "Verduras, hortaliças e derivados", kcal: 15, proteina: 1.1, carboidrato: 3.1, gordura: 0.2 },
  { nome: "Tomate, extrato", categoria: "Verduras, hortaliças e derivados", kcal: 61, proteina: 2.4, carboidrato: 15, gordura: 0.2 },
  { nome: "Tomate, molho industrializado", categoria: "Verduras, hortaliças e derivados", kcal: 38, proteina: 1.4, carboidrato: 7.7, gordura: 0.9 },
  { nome: "Tomate, purê", categoria: "Verduras, hortaliças e derivados", kcal: 28, proteina: 1.4, carboidrato: 6.9, gordura: 0 },
  { nome: "Tomate, salada", categoria: "Verduras, hortaliças e derivados", kcal: 21, proteina: 0.8, carboidrato: 5.1, gordura: 0 },
  { nome: "Vagem, crua", categoria: "Verduras, hortaliças e derivados", kcal: 25, proteina: 1.8, carboidrato: 5.3, gordura: 0.2 },
  { nome: "Abacate, cru", categoria: "Frutas e derivados", kcal: 96, proteina: 1.2, carboidrato: 6, gordura: 8.4 },
  { nome: "Abacaxi, cru", categoria: "Frutas e derivados", kcal: 48, proteina: 0.9, carboidrato: 12.3, gordura: 0.1 },
  { nome: "Abacaxi, polpa, congelada", categoria: "Frutas e derivados", kcal: 31, proteina: 0.5, carboidrato: 7.8, gordura: 0.1 },
  { nome: "Abiu, cru", categoria: "Frutas e derivados", kcal: 62, proteina: 0.8, carboidrato: 14.9, gordura: 0.7 },
  { nome: "Açaí, polpa, com xarope de guaraná e glucose", categoria: "Frutas e derivados", kcal: 110, proteina: 0.7, carboidrato: 21.5, gordura: 3.7 },
  { nome: "Açaí, polpa, congelada", categoria: "Frutas e derivados", kcal: 58, proteina: 0.8, carboidrato: 6.2, gordura: 3.9 },
  { nome: "Acerola, crua", categoria: "Frutas e derivados", kcal: 33, proteina: 0.9, carboidrato: 8, gordura: 0.2 },
  { nome: "Acerola, polpa, congelada", categoria: "Frutas e derivados", kcal: 22, proteina: 0.6, carboidrato: 5.5, gordura: 0 },
  { nome: "Ameixa, calda, enlatada", categoria: "Frutas e derivados", kcal: 183, proteina: 0.4, carboidrato: 46.9, gordura: 0 },
  { nome: "Ameixa, crua", categoria: "Frutas e derivados", kcal: 53, proteina: 0.8, carboidrato: 13.9, gordura: 0 },
  { nome: "Ameixa, em calda, enlatada, drenada", categoria: "Frutas e derivados", kcal: 177, proteina: 1, carboidrato: 47.7, gordura: 0.3 },
  { nome: "Atemóia, crua", categoria: "Frutas e derivados", kcal: 97, proteina: 1, carboidrato: 25.3, gordura: 0.3 },
  { nome: "Banana, da terra, crua", categoria: "Frutas e derivados", kcal: 128, proteina: 1.4, carboidrato: 33.7, gordura: 0.2 },
  { nome: "Banana, doce em barra", categoria: "Frutas e derivados", kcal: 280, proteina: 2.2, carboidrato: 75.7, gordura: 0.1 },
  { nome: "Banana, figo, crua", categoria: "Frutas e derivados", kcal: 105, proteina: 1.1, carboidrato: 27.8, gordura: 0.1 },
  { nome: "Banana, maçã, crua", categoria: "Frutas e derivados", kcal: 87, proteina: 1.8, carboidrato: 22.3, gordura: 0.1 },
  { nome: "Banana, nanica, crua", categoria: "Frutas e derivados", kcal: 92, proteina: 1.4, carboidrato: 23.8, gordura: 0.1 },
  { nome: "Banana, ouro, crua", categoria: "Frutas e derivados", kcal: 112, proteina: 1.5, carboidrato: 29.3, gordura: 0.2 },
  { nome: "Banana, pacova, crua", categoria: "Frutas e derivados", kcal: 78, proteina: 1.2, carboidrato: 20.3, gordura: 0.1 },
  { nome: "Banana, prata, crua", categoria: "Frutas e derivados", kcal: 98, proteina: 1.3, carboidrato: 26, gordura: 0.1 },
  { nome: "Cacau, cru", categoria: "Frutas e derivados", kcal: 74, proteina: 1, carboidrato: 19.4, gordura: 0.1 },
  { nome: "Cajá-Manga, cru", categoria: "Frutas e derivados", kcal: 46, proteina: 1.3, carboidrato: 11.4, gordura: 0 },
  { nome: "Cajá, polpa, congelada", categoria: "Frutas e derivados", kcal: 26, proteina: 0.6, carboidrato: 6.4, gordura: 0.2 },
  { nome: "Caju, cru", categoria: "Frutas e derivados", kcal: 43, proteina: 1, carboidrato: 10.3, gordura: 0.3 },
  { nome: "Caju, polpa, congelada", categoria: "Frutas e derivados", kcal: 37, proteina: 0.5, carboidrato: 9.4, gordura: 0.2 },
  { nome: "Caju, suco concentrado, envasado", categoria: "Frutas e derivados", kcal: 45, proteina: 0.4, carboidrato: 10.7, gordura: 0.2 },
  { nome: "Caqui, chocolate, cru", categoria: "Frutas e derivados", kcal: 71, proteina: 0.4, carboidrato: 19.3, gordura: 0.1 },
  { nome: "Carambola, crua", categoria: "Frutas e derivados", kcal: 46, proteina: 0.9, carboidrato: 11.5, gordura: 0.2 },
  { nome: "Ciriguela, crua", categoria: "Frutas e derivados", kcal: 76, proteina: 1.4, carboidrato: 18.9, gordura: 0.4 },
  { nome: "Cupuaçu, cru", categoria: "Frutas e derivados", kcal: 49, proteina: 1.2, carboidrato: 10.4, gordura: 1 },
  { nome: "Cupuaçu, polpa, congelada", categoria: "Frutas e derivados", kcal: 49, proteina: 0.8, carboidrato: 11.4, gordura: 0.6 },
  { nome: "Figo, cru", categoria: "Frutas e derivados", kcal: 41, proteina: 1, carboidrato: 10.2, gordura: 0.2 },
  { nome: "Figo, enlatado, em calda", categoria: "Frutas e derivados", kcal: 184, proteina: 0.6, carboidrato: 50.3, gordura: 0.2 },
  { nome: "Fruta-pão, crua", categoria: "Frutas e derivados", kcal: 67, proteina: 1.1, carboidrato: 17.2, gordura: 0.2 },
  { nome: "Goiaba, branca, com casca, crua", categoria: "Frutas e derivados", kcal: 52, proteina: 0.9, carboidrato: 12.4, gordura: 0.5 },
  { nome: "Goiaba, doce em pasta", categoria: "Frutas e derivados", kcal: 269, proteina: 0.6, carboidrato: 74.1, gordura: 0 },
  { nome: "Goiaba, doce, cascão", categoria: "Frutas e derivados", kcal: 286, proteina: 0.4, carboidrato: 78.7, gordura: 0.1 },
  { nome: "Goiaba, vermelha, com casca, crua", categoria: "Frutas e derivados", kcal: 54, proteina: 1.1, carboidrato: 13, gordura: 0.4 },
  { nome: "Graviola, crua", categoria: "Frutas e derivados", kcal: 62, proteina: 0.8, carboidrato: 15.8, gordura: 0.2 },
  { nome: "Graviola, polpa, congelada", categoria: "Frutas e derivados", kcal: 38, proteina: 0.6, carboidrato: 9.8, gordura: 0.1 },
  { nome: "Jabuticaba, crua", categoria: "Frutas e derivados", kcal: 58, proteina: 0.6, carboidrato: 15.3, gordura: 0.1 },
  { nome: "Jaca, crua", categoria: "Frutas e derivados", kcal: 88, proteina: 1.4, carboidrato: 22.5, gordura: 0.3 },
  { nome: "Jambo, cru", categoria: "Frutas e derivados", kcal: 27, proteina: 0.9, carboidrato: 6.5, gordura: 0.1 },
  { nome: "Jamelão, cru", categoria: "Frutas e derivados", kcal: 41, proteina: 0.5, carboidrato: 10.6, gordura: 0.1 },
  { nome: "Kiwi, cru", categoria: "Frutas e derivados", kcal: 51, proteina: 1.3, carboidrato: 11.5, gordura: 0.6 },
  { nome: "Laranja, baía, crua", categoria: "Frutas e derivados", kcal: 45, proteina: 1, carboidrato: 11.5, gordura: 0.1 },
  { nome: "Laranja, baía, suco", categoria: "Frutas e derivados", kcal: 37, proteina: 0.7, carboidrato: 8.7, gordura: 0 },
  { nome: "Laranja, da terra, crua", categoria: "Frutas e derivados", kcal: 51, proteina: 1.1, carboidrato: 12.9, gordura: 0.2 },
  { nome: "Laranja, da terra, suco", categoria: "Frutas e derivados", kcal: 41, proteina: 0.7, carboidrato: 9.6, gordura: 0.1 },
  { nome: "Laranja, lima, crua", categoria: "Frutas e derivados", kcal: 46, proteina: 1.1, carboidrato: 11.5, gordura: 0.1 },
  { nome: "Laranja, lima, suco", categoria: "Frutas e derivados", kcal: 39, proteina: 0.7, carboidrato: 9.2, gordura: 0.1 },
  { nome: "Laranja, pêra, crua", categoria: "Frutas e derivados", kcal: 37, proteina: 1, carboidrato: 8.9, gordura: 0.1 },
  { nome: "Laranja, pêra, suco", categoria: "Frutas e derivados", kcal: 33, proteina: 0.7, carboidrato: 7.6, gordura: 0.1 },
  { nome: "Laranja, valência, crua", categoria: "Frutas e derivados", kcal: 46, proteina: 0.8, carboidrato: 11.7, gordura: 0.2 },
  { nome: "Laranja, valência, suco", categoria: "Frutas e derivados", kcal: 36, proteina: 0.5, carboidrato: 8.6, gordura: 0.1 },
  { nome: "Limão, cravo, suco", categoria: "Frutas e derivados", kcal: 14, proteina: 0.3, carboidrato: 5.2, gordura: 0 },
  { nome: "Limão, galego, suco", categoria: "Frutas e derivados", kcal: 22, proteina: 0.6, carboidrato: 7.3, gordura: 0.1 },
  { nome: "Limão, tahiti, cru", categoria: "Frutas e derivados", kcal: 32, proteina: 0.9, carboidrato: 11.1, gordura: 0.1 },
  { nome: "Maçã, Argentina, com casca, crua", categoria: "Frutas e derivados", kcal: 63, proteina: 0.2, carboidrato: 16.6, gordura: 0.2 },
  { nome: "Maçã, Fuji, com casca, crua", categoria: "Frutas e derivados", kcal: 56, proteina: 0.3, carboidrato: 15.2, gordura: 0 },
  { nome: "Macaúba, crua", categoria: "Frutas e derivados", kcal: 404, proteina: 2.1, carboidrato: 13.9, gordura: 40.7 },
  { nome: "Mamão, doce em calda, drenado", categoria: "Frutas e derivados", kcal: 196, proteina: 0.2, carboidrato: 54, gordura: 0.1 },
  { nome: "Mamão, Formosa, cru", categoria: "Frutas e derivados", kcal: 45, proteina: 0.8, carboidrato: 11.6, gordura: 0.1 },
  { nome: "Mamão, Papaia, cru", categoria: "Frutas e derivados", kcal: 40, proteina: 0.5, carboidrato: 10.4, gordura: 0.1 },
  { nome: "Mamão verde, doce em calda, drenado", categoria: "Frutas e derivados", kcal: 209, proteina: 0.3, carboidrato: 57.6, gordura: 0.1 },
  { nome: "Manga, Haden, crua", categoria: "Frutas e derivados", kcal: 64, proteina: 0.4, carboidrato: 16.7, gordura: 0.3 },
  { nome: "Manga, Palmer, crua", categoria: "Frutas e derivados", kcal: 72, proteina: 0.4, carboidrato: 19.4, gordura: 0.2 },
  { nome: "Manga, polpa, congelada", categoria: "Frutas e derivados", kcal: 48, proteina: 0.4, carboidrato: 12.5, gordura: 0.2 },
  { nome: "Manga, Tommy Atkins, crua", categoria: "Frutas e derivados", kcal: 51, proteina: 0.9, carboidrato: 12.8, gordura: 0.2 },
  { nome: "Maracujá, cru", categoria: "Frutas e derivados", kcal: 68, proteina: 2, carboidrato: 12.3, gordura: 2.1 },
  { nome: "Maracujá, polpa, congelada", categoria: "Frutas e derivados", kcal: 39, proteina: 0.8, carboidrato: 9.6, gordura: 0.2 },
  { nome: "Maracujá, suco concentrado, envasado", categoria: "Frutas e derivados", kcal: 42, proteina: 0.8, carboidrato: 9.6, gordura: 0.2 },
  { nome: "Melancia, crua", categoria: "Frutas e derivados", kcal: 33, proteina: 0.9, carboidrato: 8.1, gordura: 0 },
  { nome: "Melão, cru", categoria: "Frutas e derivados", kcal: 29, proteina: 0.7, carboidrato: 7.5, gordura: 0 },
  { nome: "Mexerica, Murcote, crua", categoria: "Frutas e derivados", kcal: 58, proteina: 0.9, carboidrato: 14.9, gordura: 0.1 },
  { nome: "Mexerica, Rio, crua", categoria: "Frutas e derivados", kcal: 37, proteina: 0.7, carboidrato: 9.3, gordura: 0.1 },
  { nome: "Morango, cru", categoria: "Frutas e derivados", kcal: 30, proteina: 0.9, carboidrato: 6.8, gordura: 0.3 },
  { nome: "Nêspera, crua", categoria: "Frutas e derivados", kcal: 43, proteina: 0.3, carboidrato: 11.5, gordura: 0 },
  { nome: "Pequi, cru", categoria: "Frutas e derivados", kcal: 205, proteina: 2.3, carboidrato: 13, gordura: 18 },
  { nome: "Pêra, Park, crua", categoria: "Frutas e derivados", kcal: 61, proteina: 0.2, carboidrato: 16.1, gordura: 0.2 },
  { nome: "Pêra, Williams, crua", categoria: "Frutas e derivados", kcal: 53, proteina: 0.6, carboidrato: 14, gordura: 0.1 },
  { nome: "Pêssego, Aurora, cru", categoria: "Frutas e derivados", kcal: 36, proteina: 0.8, carboidrato: 9.3, gordura: 0 },
  { nome: "Pêssego, enlatado, em calda", categoria: "Frutas e derivados", kcal: 63, proteina: 0.7, carboidrato: 16.9, gordura: 0 },
  { nome: "Pinha, crua", categoria: "Frutas e derivados", kcal: 88, proteina: 1.5, carboidrato: 22.4, gordura: 0.3 },
  { nome: "Pitanga, crua", categoria: "Frutas e derivados", kcal: 41, proteina: 0.9, carboidrato: 10.2, gordura: 0.2 },
  { nome: "Pitanga, polpa, congelada", categoria: "Frutas e derivados", kcal: 19, proteina: 0.3, carboidrato: 4.8, gordura: 0.1 },
  { nome: "Romã, crua", categoria: "Frutas e derivados", kcal: 56, proteina: 0.4, carboidrato: 15.1, gordura: 0 },
  { nome: "Tamarindo, cru", categoria: "Frutas e derivados", kcal: 276, proteina: 3.2, carboidrato: 72.5, gordura: 0.5 },
  { nome: "Tangerina, Poncã, crua", categoria: "Frutas e derivados", kcal: 38, proteina: 0.8, carboidrato: 9.6, gordura: 0.1 },
  { nome: "Tangerina, Poncã, suco", categoria: "Frutas e derivados", kcal: 36, proteina: 0.5, carboidrato: 8.8, gordura: 0 },
  { nome: "Tucumã, cru", categoria: "Frutas e derivados", kcal: 262, proteina: 2.1, carboidrato: 26.5, gordura: 19.1 },
  { nome: "Umbu, cru", categoria: "Frutas e derivados", kcal: 37, proteina: 0.8, carboidrato: 9.4, gordura: 0 },
  { nome: "Umbu, polpa, congelada", categoria: "Frutas e derivados", kcal: 34, proteina: 0.5, carboidrato: 8.8, gordura: 0.1 },
  { nome: "Uva, Itália, crua", categoria: "Frutas e derivados", kcal: 53, proteina: 0.7, carboidrato: 13.6, gordura: 0.2 },
  { nome: "Uva, Rubi, crua", categoria: "Frutas e derivados", kcal: 49, proteina: 0.6, carboidrato: 12.7, gordura: 0.2 },
  { nome: "Uva, suco concentrado, envasado", categoria: "Frutas e derivados", kcal: 58, proteina: 0, carboidrato: 14.7, gordura: 0 },
  { nome: "Azeite, de dendê", categoria: "Gorduras e óleos", kcal: 884, proteina: 0, carboidrato: 0, gordura: 100 },
  { nome: "Azeite, de oliva, extra virgem", categoria: "Gorduras e óleos", kcal: 884, proteina: 0, carboidrato: 0, gordura: 100 },
  { nome: "Manteiga, com sal", categoria: "Gorduras e óleos", kcal: 726, proteina: 0.4, carboidrato: 0.1, gordura: 82.4 },
  { nome: "Manteiga, sem sal", categoria: "Gorduras e óleos", kcal: 758, proteina: 0.4, carboidrato: 0, gordura: 86 },
  { nome: "Margarina, com óleo hidrogenado, com sal (65% de lipídeos)", categoria: "Gorduras e óleos", kcal: 596, proteina: 0, carboidrato: 0, gordura: 67.4 },
  { nome: "Margarina, com óleo hidrogenado, sem sal (80% de lipídeos)", categoria: "Gorduras e óleos", kcal: 723, proteina: 0, carboidrato: 0, gordura: 81.7 },
  { nome: "Margarina, com óleo interesterificado, com sal (65%de lipídeos)", categoria: "Gorduras e óleos", kcal: 594, proteina: 0, carboidrato: 0, gordura: 67.2 },
  { nome: "Margarina, com óleo interesterificado, sem sal (65% de lipídeos)", categoria: "Gorduras e óleos", kcal: 593, proteina: 0, carboidrato: 0, gordura: 67.1 },
  { nome: "Óleo, de babaçu", categoria: "Gorduras e óleos", kcal: 884, proteina: 0, carboidrato: 0, gordura: 100 },
  { nome: "Óleo, de canola", categoria: "Gorduras e óleos", kcal: 884, proteina: 0, carboidrato: 0, gordura: 100 },
  { nome: "Óleo, de girassol", categoria: "Gorduras e óleos", kcal: 884, proteina: 0, carboidrato: 0, gordura: 100 },
  { nome: "Óleo, de milho", categoria: "Gorduras e óleos", kcal: 884, proteina: 0, carboidrato: 0, gordura: 100 },
  { nome: "Óleo, de pequi", categoria: "Gorduras e óleos", kcal: 884, proteina: 0, carboidrato: 0, gordura: 100 },
  { nome: "Óleo, de soja", categoria: "Gorduras e óleos", kcal: 884, proteina: 0, carboidrato: 0, gordura: 100 },
  { nome: "Abadejo, filé, congelado, assado", categoria: "Pescados e frutos do mar", kcal: 112, proteina: 23.5, carboidrato: 0, gordura: 1.2 },
  { nome: "Abadejo, filé, congelado,cozido", categoria: "Pescados e frutos do mar", kcal: 91, proteina: 19.3, carboidrato: 0, gordura: 0.9 },
  { nome: "Abadejo, filé, congelado, cru", categoria: "Pescados e frutos do mar", kcal: 59, proteina: 13.1, carboidrato: 0, gordura: 0.4 },
  { nome: "Abadejo, filé, congelado, grelhado", categoria: "Pescados e frutos do mar", kcal: 130, proteina: 27.6, carboidrato: 0, gordura: 1.3 },
  { nome: "Atum, conserva em óleo", categoria: "Pescados e frutos do mar", kcal: 166, proteina: 26.2, carboidrato: 0, gordura: 6 },
  { nome: "Atum, fresco, cru", categoria: "Pescados e frutos do mar", kcal: 118, proteina: 25.7, carboidrato: 0, gordura: 0.9 },
  { nome: "Bacalhau, salgado, cru", categoria: "Pescados e frutos do mar", kcal: 136, proteina: 29, carboidrato: 0, gordura: 1.3 },
  { nome: "Bacalhau, salgado, refogado", categoria: "Pescados e frutos do mar", kcal: 140, proteina: 24, carboidrato: 1.2, gordura: 3.6 },
  { nome: "Cação, posta, com farinha de trigo, frita", categoria: "Pescados e frutos do mar", kcal: 208, proteina: 25, carboidrato: 3.1, gordura: 10 },
  { nome: "Cação, posta, cozida", categoria: "Pescados e frutos do mar", kcal: 116, proteina: 25.6, carboidrato: 0, gordura: 0.7 },
  { nome: "Cação, posta, crua", categoria: "Pescados e frutos do mar", kcal: 83, proteina: 17.9, carboidrato: 0, gordura: 0.8 },
  { nome: "Camarão, Rio Grande, grande, cozido", categoria: "Pescados e frutos do mar", kcal: 90, proteina: 19, carboidrato: 0, gordura: 1 },
  { nome: "Camarão, Rio Grande, grande, cru", categoria: "Pescados e frutos do mar", kcal: 47, proteina: 10, carboidrato: 0, gordura: 0.5 },
  { nome: "Camarão, Sete Barbas, sem cabeça, com casca, frito", categoria: "Pescados e frutos do mar", kcal: 231, proteina: 18.4, carboidrato: 2.9, gordura: 15.6 },
  { nome: "Caranguejo, cozido", categoria: "Pescados e frutos do mar", kcal: 83, proteina: 18.5, carboidrato: 0, gordura: 0.4 },
  { nome: "Corimba, cru", categoria: "Pescados e frutos do mar", kcal: 128, proteina: 17.4, carboidrato: 0, gordura: 6 },
  { nome: "Corimbatá, assado", categoria: "Pescados e frutos do mar", kcal: 261, proteina: 19.9, carboidrato: 0, gordura: 19.6 },
  { nome: "Corimbatá, cozido", categoria: "Pescados e frutos do mar", kcal: 239, proteina: 20.1, carboidrato: 0, gordura: 16.9 },
  { nome: "Corvina de água doce, crua", categoria: "Pescados e frutos do mar", kcal: 101, proteina: 18.9, carboidrato: 0, gordura: 2.2 },
  { nome: "Corvina do mar, crua", categoria: "Pescados e frutos do mar", kcal: 94, proteina: 18.6, carboidrato: 0, gordura: 1.6 },
  { nome: "Corvina grande, assada", categoria: "Pescados e frutos do mar", kcal: 147, proteina: 26.8, carboidrato: 0, gordura: 3.6 },
  { nome: "Corvina grande, cozida", categoria: "Pescados e frutos do mar", kcal: 100, proteina: 23.4, carboidrato: 0, gordura: 2.6 },
  { nome: "Dourada de água doce, fresca", categoria: "Pescados e frutos do mar", kcal: 131, proteina: 18.8, carboidrato: 0, gordura: 5.6 },
  { nome: "Lambari, congelado, cru", categoria: "Pescados e frutos do mar", kcal: 131, proteina: 16.8, carboidrato: 0, gordura: 6.5 },
  { nome: "Lambari, congelado, frito", categoria: "Pescados e frutos do mar", kcal: 327, proteina: 28.4, carboidrato: 0, gordura: 22.8 },
  { nome: "Lambari, fresco, cru", categoria: "Pescados e frutos do mar", kcal: 152, proteina: 15.7, carboidrato: 0, gordura: 9.4 },
  { nome: "Manjuba, com farinha de trigo, frita", categoria: "Pescados e frutos do mar", kcal: 344, proteina: 23.5, carboidrato: 10.2, gordura: 22.6 },
  { nome: "Manjuba, frita", categoria: "Pescados e frutos do mar", kcal: 349, proteina: 30.1, carboidrato: 0, gordura: 24.5 },
  { nome: "Merluza, filé, assado", categoria: "Pescados e frutos do mar", kcal: 122, proteina: 26.6, carboidrato: 0, gordura: 0.9 },
  { nome: "Merluza, filé, cru", categoria: "Pescados e frutos do mar", kcal: 89, proteina: 16.6, carboidrato: 0, gordura: 2 },
  { nome: "Merluza, filé, frito", categoria: "Pescados e frutos do mar", kcal: 192, proteina: 26.9, carboidrato: 0, gordura: 8.5 },
  { nome: "Pescada, branca, crua", categoria: "Pescados e frutos do mar", kcal: 111, proteina: 16.3, carboidrato: 0, gordura: 4.6 },
  { nome: "Pescada, branca, frita", categoria: "Pescados e frutos do mar", kcal: 223, proteina: 27.4, carboidrato: 0, gordura: 11.8 },
  { nome: "Pescada, filé, com farinha de trigo, frito", categoria: "Pescados e frutos do mar", kcal: 283, proteina: 21.4, carboidrato: 5, gordura: 19.1 },
  { nome: "Pescada, filé, cru", categoria: "Pescados e frutos do mar", kcal: 107, proteina: 16.7, carboidrato: 0, gordura: 4 },
  { nome: "Pescada, filé, frito", categoria: "Pescados e frutos do mar", kcal: 154, proteina: 28.6, carboidrato: 0, gordura: 3.6 },
  { nome: "Pescada, filé, molho escabeche", categoria: "Pescados e frutos do mar", kcal: 142, proteina: 11.8, carboidrato: 5, gordura: 8 },
  { nome: "Pescadinha, crua", categoria: "Pescados e frutos do mar", kcal: 76, proteina: 15.5, carboidrato: 0, gordura: 1.1 },
  { nome: "Pintado, assado", categoria: "Pescados e frutos do mar", kcal: 192, proteina: 36.5, carboidrato: 0, gordura: 4 },
  { nome: "Pintado, cru", categoria: "Pescados e frutos do mar", kcal: 91, proteina: 18.6, carboidrato: 0, gordura: 1.3 },
  { nome: "Pintado, grelhado", categoria: "Pescados e frutos do mar", kcal: 152, proteina: 30.8, carboidrato: 0, gordura: 2.3 },
  { nome: "Porquinho, cru", categoria: "Pescados e frutos do mar", kcal: 93, proteina: 20.5, carboidrato: 0, gordura: 0.6 },
  { nome: "Salmão, filé, com pele, fresco,  grelhado", categoria: "Pescados e frutos do mar", kcal: 229, proteina: 23.9, carboidrato: 0, gordura: 14 },
  { nome: "Salmão, sem pele, fresco, cru", categoria: "Pescados e frutos do mar", kcal: 170, proteina: 19.3, carboidrato: 0, gordura: 9.7 },
  { nome: "Salmão, sem pele, fresco, grelhado", categoria: "Pescados e frutos do mar", kcal: 243, proteina: 26.1, carboidrato: 0, gordura: 14.5 },
  { nome: "Sardinha, assada", categoria: "Pescados e frutos do mar", kcal: 164, proteina: 32.2, carboidrato: 0, gordura: 3 },
  { nome: "Sardinha, conserva em óleo", categoria: "Pescados e frutos do mar", kcal: 285, proteina: 15.9, carboidrato: 0, gordura: 24 },
  { nome: "Sardinha, frita", categoria: "Pescados e frutos do mar", kcal: 257, proteina: 33.4, carboidrato: 0, gordura: 12.7 },
  { nome: "Sardinha, inteira, crua", categoria: "Pescados e frutos do mar", kcal: 114, proteina: 21.1, carboidrato: 0, gordura: 2.7 },
  { nome: "Tucunaré, filé, congelado, cru", categoria: "Pescados e frutos do mar", kcal: 88, proteina: 18, carboidrato: 0, gordura: 1.2 },
  { nome: "Apresuntado", categoria: "Carnes e derivados", kcal: 129, proteina: 13.5, carboidrato: 2.9, gordura: 6.7 },
  { nome: "Caldo de carne, tablete", categoria: "Carnes e derivados", kcal: 241, proteina: 7.8, carboidrato: 15.1, gordura: 16.6 },
  { nome: "Caldo de galinha, tablete", categoria: "Carnes e derivados", kcal: 251, proteina: 6.3, carboidrato: 10.6, gordura: 20.4 },
  { nome: "Carne, bovina, acém, moído, cozido", categoria: "Carnes e derivados", kcal: 212, proteina: 26.7, carboidrato: 0, gordura: 10.9 },
  { nome: "Carne, bovina, acém, moído, cru", categoria: "Carnes e derivados", kcal: 137, proteina: 19.4, carboidrato: 0, gordura: 5.9 },
  { nome: "Carne, bovina, acém, sem gordura, cozido", categoria: "Carnes e derivados", kcal: 215, proteina: 27.3, carboidrato: 0, gordura: 10.9 },
  { nome: "Carne, bovina, acém, sem gordura, cru", categoria: "Carnes e derivados", kcal: 144, proteina: 20.8, carboidrato: 0, gordura: 6.1 },
  { nome: "Carne, bovina, almôndegas, cruas", categoria: "Carnes e derivados", kcal: 189, proteina: 12.3, carboidrato: 9.8, gordura: 11.2 },
  { nome: "Carne, bovina, almôndegas, fritas", categoria: "Carnes e derivados", kcal: 272, proteina: 18.2, carboidrato: 14.3, gordura: 15.8 },
  { nome: "Carne, bovina, bucho, cozido", categoria: "Carnes e derivados", kcal: 133, proteina: 21.6, carboidrato: 0, gordura: 4.5 },
  { nome: "Carne, bovina, bucho, cru", categoria: "Carnes e derivados", kcal: 137, proteina: 20.5, carboidrato: 0, gordura: 5.5 },
  { nome: "Carne, bovina, capa de contra-filé, com gordura, crua", categoria: "Carnes e derivados", kcal: 217, proteina: 19.2, carboidrato: 0, gordura: 15 },
  { nome: "Carne, bovina, capa de contra-filé, com gordura, grelhada", categoria: "Carnes e derivados", kcal: 312, proteina: 30.7, carboidrato: 0, gordura: 20 },
  { nome: "Carne, bovina, capa de contra-filé, sem gordura, crua", categoria: "Carnes e derivados", kcal: 131, proteina: 21.5, carboidrato: 0, gordura: 4.3 },
  { nome: "Carne, bovina, capa de contra-filé, sem gordura, grelhada", categoria: "Carnes e derivados", kcal: 239, proteina: 35.1, carboidrato: 0, gordura: 10 },
  { nome: "Carne, bovina, charque, cozido", categoria: "Carnes e derivados", kcal: 263, proteina: 36.4, carboidrato: 0, gordura: 11.9 },
  { nome: "Carne, bovina, charque, cru", categoria: "Carnes e derivados", kcal: 249, proteina: 22.7, carboidrato: 0, gordura: 16.8 },
  { nome: "Carne, bovina, contra-filé, à milanesa", categoria: "Carnes e derivados", kcal: 352, proteina: 20.6, carboidrato: 12.2, gordura: 24 },
  { nome: "Carne, bovina, contra-filé de costela, cru", categoria: "Carnes e derivados", kcal: 202, proteina: 19.8, carboidrato: 0, gordura: 13.1 },
  { nome: "Carne, bovina, contra-filé de costela, grelhado", categoria: "Carnes e derivados", kcal: 275, proteina: 29.9, carboidrato: 0, gordura: 16.3 },
  { nome: "Carne, bovina, contra-filé, com gordura, cru", categoria: "Carnes e derivados", kcal: 206, proteina: 21.2, carboidrato: 0, gordura: 12.8 },
  { nome: "Carne, bovina, contra-filé, com gordura, grelhado", categoria: "Carnes e derivados", kcal: 278, proteina: 32.4, carboidrato: 0, gordura: 15.5 },
  { nome: "Carne, bovina, contra-filé, sem gordura, cru", categoria: "Carnes e derivados", kcal: 157, proteina: 24, carboidrato: 0, gordura: 6 },
  { nome: "Carne, bovina, contra-filé, sem gordura, grelhado", categoria: "Carnes e derivados", kcal: 194, proteina: 35.9, carboidrato: 0, gordura: 4.5 },
  { nome: "Carne, bovina, costela, assada", categoria: "Carnes e derivados", kcal: 373, proteina: 28.8, carboidrato: 0, gordura: 27.7 },
  { nome: "Carne, bovina, costela, crua", categoria: "Carnes e derivados", kcal: 358, proteina: 16.7, carboidrato: 0, gordura: 31.8 },
  { nome: "Carne, bovina, coxão duro, sem gordura, cozido", categoria: "Carnes e derivados", kcal: 217, proteina: 31.9, carboidrato: 0, gordura: 8.9 },
  { nome: "Carne, bovina, coxão duro, sem gordura, cru", categoria: "Carnes e derivados", kcal: 148, proteina: 21.5, carboidrato: 0, gordura: 6.2 },
  { nome: "Carne, bovina, coxão mole, sem gordura, cozido", categoria: "Carnes e derivados", kcal: 219, proteina: 32.4, carboidrato: 0, gordura: 8.9 },
  { nome: "Carne, bovina, coxão mole, sem gordura, cru", categoria: "Carnes e derivados", kcal: 169, proteina: 21.2, carboidrato: 0, gordura: 8.7 },
  { nome: "Carne, bovina, cupim, assado", categoria: "Carnes e derivados", kcal: 330, proteina: 28.6, carboidrato: 0, gordura: 23 },
  { nome: "Carne, bovina, cupim, cru", categoria: "Carnes e derivados", kcal: 221, proteina: 19.5, carboidrato: 0, gordura: 15.3 },
  { nome: "Carne, bovina, fígado, cru", categoria: "Carnes e derivados", kcal: 141, proteina: 20.7, carboidrato: 1.1, gordura: 5.4 },
  { nome: "Carne, bovina, fígado, grelhado", categoria: "Carnes e derivados", kcal: 225, proteina: 29.9, carboidrato: 4.2, gordura: 9 },
  { nome: "Carne, bovina, filé mingnon, sem gordura, cru", categoria: "Carnes e derivados", kcal: 143, proteina: 21.6, carboidrato: 0, gordura: 5.6 },
  { nome: "Carne, bovina, filé mingnon, sem gordura, grelhado", categoria: "Carnes e derivados", kcal: 220, proteina: 32.8, carboidrato: 0, gordura: 8.8 },
  { nome: "Carne, bovina, flanco, sem gordura, cozido", categoria: "Carnes e derivados", kcal: 196, proteina: 29.4, carboidrato: 0, gordura: 7.8 },
  { nome: "Carne, bovina, flanco, sem gordura, cru", categoria: "Carnes e derivados", kcal: 141, proteina: 20, carboidrato: 0, gordura: 6.2 },
  { nome: "Carne, bovina, fraldinha, com gordura, cozida", categoria: "Carnes e derivados", kcal: 338, proteina: 24.2, carboidrato: 0, gordura: 26 },
  { nome: "Carne, bovina, fraldinha, com gordura, crua", categoria: "Carnes e derivados", kcal: 221, proteina: 17.6, carboidrato: 0, gordura: 16.1 },
  { nome: "Carne, bovina, lagarto, cozido", categoria: "Carnes e derivados", kcal: 222, proteina: 32.9, carboidrato: 0, gordura: 9.1 },
  { nome: "Carne, bovina, lagarto, cru", categoria: "Carnes e derivados", kcal: 135, proteina: 20.5, carboidrato: 0, gordura: 5.2 },
  { nome: "Carne, bovina, língua, cozida", categoria: "Carnes e derivados", kcal: 315, proteina: 21.4, carboidrato: 0, gordura: 24.8 },
  { nome: "Carne, bovina, língua, crua", categoria: "Carnes e derivados", kcal: 215, proteina: 17.1, carboidrato: 0, gordura: 15.8 },
  { nome: "Carne, bovina, maminha, crua", categoria: "Carnes e derivados", kcal: 153, proteina: 20.9, carboidrato: 0, gordura: 7 },
  { nome: "Carne, bovina, maminha, grelhada", categoria: "Carnes e derivados", kcal: 153, proteina: 30.7, carboidrato: 0, gordura: 2.4 },
  { nome: "Carne, bovina, miolo de alcatra, sem gordura, cru", categoria: "Carnes e derivados", kcal: 163, proteina: 21.6, carboidrato: 0, gordura: 7.8 },
  { nome: "Carne, bovina, miolo de alcatra, sem gordura, grelhado", categoria: "Carnes e derivados", kcal: 241, proteina: 31.9, carboidrato: 0, gordura: 11.6 },
  { nome: "Carne, bovina, músculo, sem gordura, cozido", categoria: "Carnes e derivados", kcal: 194, proteina: 31.2, carboidrato: 0, gordura: 6.7 },
  { nome: "Carne, bovina, músculo, sem gordura, cru", categoria: "Carnes e derivados", kcal: 142, proteina: 21.6, carboidrato: 0, gordura: 5.5 },
  { nome: "Carne, bovina, paleta, com gordura, crua", categoria: "Carnes e derivados", kcal: 159, proteina: 21.4, carboidrato: 0, gordura: 7.5 },
  { nome: "Carne, bovina, paleta, sem gordura, cozida", categoria: "Carnes e derivados", kcal: 194, proteina: 29.7, carboidrato: 0, gordura: 7.4 },
  { nome: "Carne, bovina, paleta, sem gordura, crua", categoria: "Carnes e derivados", kcal: 141, proteina: 21, carboidrato: 0, gordura: 5.7 },
  { nome: "Carne, bovina, patinho, sem gordura, cru", categoria: "Carnes e derivados", kcal: 133, proteina: 21.7, carboidrato: 0, gordura: 4.5 },
  { nome: "Carne, bovina, patinho, sem gordura, grelhado", categoria: "Carnes e derivados", kcal: 219, proteina: 35.9, carboidrato: 0, gordura: 7.3 },
  { nome: "Carne, bovina, peito, sem gordura, cozido", categoria: "Carnes e derivados", kcal: 338, proteina: 22.2, carboidrato: 0, gordura: 27 },
  { nome: "Carne, bovina, peito, sem gordura, cru", categoria: "Carnes e derivados", kcal: 259, proteina: 17.6, carboidrato: 0, gordura: 20.4 },
  { nome: "Carne, bovina, picanha, com gordura, crua", categoria: "Carnes e derivados", kcal: 213, proteina: 18.8, carboidrato: 0, gordura: 14.7 },
  { nome: "Carne, bovina, picanha, com gordura, grelhada", categoria: "Carnes e derivados", kcal: 289, proteina: 26.4, carboidrato: 0, gordura: 19.5 },
  { nome: "Carne, bovina, picanha, sem gordura, crua", categoria: "Carnes e derivados", kcal: 134, proteina: 21.3, carboidrato: 0, gordura: 4.7 },
  { nome: "Carne, bovina, picanha, sem gordura, grelhada", categoria: "Carnes e derivados", kcal: 238, proteina: 31.9, carboidrato: 0, gordura: 11.3 },
  { nome: "Carne, bovina, seca, cozida", categoria: "Carnes e derivados", kcal: 313, proteina: 26.9, carboidrato: 0, gordura: 21.9 },
  { nome: "Carne, bovina, seca, crua", categoria: "Carnes e derivados", kcal: 313, proteina: 19.7, carboidrato: 0, gordura: 25.4 },
  { nome: "Coxinha de frango, frita", categoria: "Carnes e derivados", kcal: 283, proteina: 9.6, carboidrato: 34.5, gordura: 11.8 },
  { nome: "Croquete, de carne, cru", categoria: "Carnes e derivados", kcal: 246, proteina: 12, carboidrato: 13.9, gordura: 15.6 },
  { nome: "Croquete, de carne, frito", categoria: "Carnes e derivados", kcal: 347, proteina: 16.9, carboidrato: 18.1, gordura: 22.7 },
  { nome: "Empada de frango, pré-cozida, assada", categoria: "Carnes e derivados", kcal: 358, proteina: 6.9, carboidrato: 47.5, gordura: 15.6 },
  { nome: "Empada, de frango, pré-cozida", categoria: "Carnes e derivados", kcal: 377, proteina: 7.3, carboidrato: 35.5, gordura: 22.9 },
  { nome: "Frango, asa, com pele, crua", categoria: "Carnes e derivados", kcal: 213, proteina: 18.1, carboidrato: 0, gordura: 15.1 },
  { nome: "Frango, caipira, inteiro, com pele, cozido", categoria: "Carnes e derivados", kcal: 243, proteina: 23.9, carboidrato: 0, gordura: 15.6 },
  { nome: "Frango, caipira, inteiro, sem pele, cozido", categoria: "Carnes e derivados", kcal: 196, proteina: 29.6, carboidrato: 0, gordura: 7.7 },
  { nome: "Frango, coração, cru", categoria: "Carnes e derivados", kcal: 222, proteina: 12.6, carboidrato: 0, gordura: 18.6 },
  { nome: "Frango, coração, grelhado", categoria: "Carnes e derivados", kcal: 207, proteina: 22.4, carboidrato: 0.6, gordura: 12.1 },
  { nome: "Frango, coxa, com pele, assada", categoria: "Carnes e derivados", kcal: 215, proteina: 28.5, carboidrato: 0.1, gordura: 10.4 },
  { nome: "Frango, coxa, com pele, crua", categoria: "Carnes e derivados", kcal: 161, proteina: 17.1, carboidrato: 0, gordura: 9.8 },
  { nome: "Frango, coxa, sem pele, cozida", categoria: "Carnes e derivados", kcal: 167, proteina: 26.9, carboidrato: 0, gordura: 5.8 },
  { nome: "Frango, coxa, sem pele, crua", categoria: "Carnes e derivados", kcal: 120, proteina: 17.8, carboidrato: 0, gordura: 4.9 },
  { nome: "Frango, fígado, cru", categoria: "Carnes e derivados", kcal: 106, proteina: 17.6, carboidrato: 0, gordura: 3.5 },
  { nome: "Frango, filé, à milanesa", categoria: "Carnes e derivados", kcal: 221, proteina: 28.5, carboidrato: 7.5, gordura: 7.8 },
  { nome: "Frango, inteiro, com pele, cru", categoria: "Carnes e derivados", kcal: 226, proteina: 16.4, carboidrato: 0, gordura: 17.3 },
  { nome: "Frango, inteiro, sem pele, assado", categoria: "Carnes e derivados", kcal: 187, proteina: 28, carboidrato: 0, gordura: 7.5 },
  { nome: "Frango, inteiro, sem pele, cozido", categoria: "Carnes e derivados", kcal: 170, proteina: 25, carboidrato: 0, gordura: 7.1 },
  { nome: "Frango, inteiro, sem pele, cru", categoria: "Carnes e derivados", kcal: 129, proteina: 20.6, carboidrato: 0, gordura: 4.6 },
  { nome: "Frango, peito, com pele, assado", categoria: "Carnes e derivados", kcal: 212, proteina: 33.4, carboidrato: 0, gordura: 7.6 },
  { nome: "Frango, peito, com pele, cru", categoria: "Carnes e derivados", kcal: 149, proteina: 20.8, carboidrato: 0, gordura: 6.7 },
  { nome: "Frango, peito, sem pele, cozido", categoria: "Carnes e derivados", kcal: 163, proteina: 31.5, carboidrato: 0, gordura: 3.2 },
  { nome: "Frango, peito, sem pele, cru", categoria: "Carnes e derivados", kcal: 119, proteina: 21.5, carboidrato: 0, gordura: 3 },
  { nome: "Frango, peito, sem pele, grelhado", categoria: "Carnes e derivados", kcal: 159, proteina: 32, carboidrato: 0, gordura: 2.5 },
  { nome: "Frango, sobrecoxa, com pele, assada", categoria: "Carnes e derivados", kcal: 260, proteina: 28.7, carboidrato: 0, gordura: 15.2 },
  { nome: "Frango, sobrecoxa, com pele, crua", categoria: "Carnes e derivados", kcal: 255, proteina: 15.5, carboidrato: 0, gordura: 20.9 },
  { nome: "Frango, sobrecoxa, sem pele, assada", categoria: "Carnes e derivados", kcal: 233, proteina: 29.2, carboidrato: 0, gordura: 12 },
  { nome: "Frango, sobrecoxa, sem pele, crua", categoria: "Carnes e derivados", kcal: 162, proteina: 17.6, carboidrato: 0, gordura: 9.6 },
  { nome: "Hambúrguer, bovino, cru", categoria: "Carnes e derivados", kcal: 215, proteina: 13.2, carboidrato: 4.2, gordura: 16.2 },
  { nome: "Hambúrguer, bovino, frito", categoria: "Carnes e derivados", kcal: 258, proteina: 20, carboidrato: 6.3, gordura: 17 },
  { nome: "Hambúrguer, bovino, grelhado", categoria: "Carnes e derivados", kcal: 210, proteina: 13.2, carboidrato: 11.3, gordura: 12.4 },
  { nome: "Lingüiça, frango, crua", categoria: "Carnes e derivados", kcal: 218, proteina: 14.2, carboidrato: 0, gordura: 17.4 },
  { nome: "Lingüiça, frango, frita", categoria: "Carnes e derivados", kcal: 245, proteina: 18.3, carboidrato: 0, gordura: 18.5 },
  { nome: "Lingüiça, frango, grelhada", categoria: "Carnes e derivados", kcal: 244, proteina: 18.2, carboidrato: 0, gordura: 18.4 },
  { nome: "Lingüiça, porco, crua", categoria: "Carnes e derivados", kcal: 227, proteina: 16.1, carboidrato: 0, gordura: 17.6 },
  { nome: "Lingüiça, porco, frita", categoria: "Carnes e derivados", kcal: 280, proteina: 20.5, carboidrato: 0, gordura: 21.3 },
  { nome: "Lingüiça, porco, grelhada", categoria: "Carnes e derivados", kcal: 296, proteina: 23.2, carboidrato: 0, gordura: 21.9 },
  { nome: "Mortadela", categoria: "Carnes e derivados", kcal: 269, proteina: 12, carboidrato: 5.8, gordura: 21.6 },
  { nome: "Peru, congelado, assado", categoria: "Carnes e derivados", kcal: 163, proteina: 26.2, carboidrato: 0, gordura: 5.7 },
  { nome: "Peru, congelado, cru", categoria: "Carnes e derivados", kcal: 94, proteina: 18.1, carboidrato: 0, gordura: 1.8 },
  { nome: "Porco, bisteca, crua", categoria: "Carnes e derivados", kcal: 164, proteina: 21.5, carboidrato: 0, gordura: 8 },
  { nome: "Porco, bisteca, frita", categoria: "Carnes e derivados", kcal: 311, proteina: 33.7, carboidrato: 0, gordura: 18.5 },
  { nome: "Porco, bisteca, grelhada", categoria: "Carnes e derivados", kcal: 280, proteina: 28.9, carboidrato: 0, gordura: 17.4 },
  { nome: "Porco, costela, assada", categoria: "Carnes e derivados", kcal: 402, proteina: 30.2, carboidrato: 0, gordura: 30.3 },
  { nome: "Porco, costela, crua", categoria: "Carnes e derivados", kcal: 256, proteina: 18, carboidrato: 0, gordura: 19.8 },
  { nome: "Porco, lombo, assado", categoria: "Carnes e derivados", kcal: 210, proteina: 35.7, carboidrato: 0, gordura: 6.4 },
  { nome: "Porco, lombo, cru", categoria: "Carnes e derivados", kcal: 176, proteina: 22.6, carboidrato: 0, gordura: 8.8 },
  { nome: "Porco, orelha, salgada, crua", categoria: "Carnes e derivados", kcal: 258, proteina: 18.5, carboidrato: 0, gordura: 19.9 },
  { nome: "Porco, pernil, assado", categoria: "Carnes e derivados", kcal: 262, proteina: 32.1, carboidrato: 0, gordura: 13.9 },
  { nome: "Porco, pernil, cru", categoria: "Carnes e derivados", kcal: 186, proteina: 20.1, carboidrato: 0, gordura: 11.1 },
  { nome: "Porco, rabo, salgado, cru", categoria: "Carnes e derivados", kcal: 377, proteina: 15.6, carboidrato: 0, gordura: 34.5 },
  { nome: "Presunto, com capa de gordura", categoria: "Carnes e derivados", kcal: 128, proteina: 14.4, carboidrato: 1.4, gordura: 6.8 },
  { nome: "Presunto, sem capa de gordura", categoria: "Carnes e derivados", kcal: 94, proteina: 14.3, carboidrato: 2.1, gordura: 2.7 },
  { nome: "Quibe, assado", categoria: "Carnes e derivados", kcal: 136, proteina: 14.6, carboidrato: 12.9, gordura: 2.7 },
  { nome: "Quibe, cru", categoria: "Carnes e derivados", kcal: 109, proteina: 12.4, carboidrato: 10.8, gordura: 1.7 },
  { nome: "Quibe, frito", categoria: "Carnes e derivados", kcal: 254, proteina: 14.9, carboidrato: 12.3, gordura: 15.8 },
  { nome: "Salame", categoria: "Carnes e derivados", kcal: 398, proteina: 25.8, carboidrato: 2.9, gordura: 30.6 },
  { nome: "Toucinho, cru", categoria: "Carnes e derivados", kcal: 593, proteina: 11.5, carboidrato: 0, gordura: 60.3 },
  { nome: "Toucinho, frito", categoria: "Carnes e derivados", kcal: 697, proteina: 27.3, carboidrato: 0, gordura: 64.3 },
  { nome: "Bebida láctea, pêssego", categoria: "Leite e derivados", kcal: 55, proteina: 2.1, carboidrato: 7.6, gordura: 1.9 },
  { nome: "Creme de Leite", categoria: "Leite e derivados", kcal: 221, proteina: 1.5, carboidrato: 4.5, gordura: 22.5 },
  { nome: "Iogurte, natural", categoria: "Leite e derivados", kcal: 51, proteina: 4.1, carboidrato: 1.9, gordura: 3 },
  { nome: "Iogurte, natural, desnatado", categoria: "Leite e derivados", kcal: 41, proteina: 3.8, carboidrato: 5.8, gordura: 0.3 },
  { nome: "Iogurte, sabor abacaxi", categoria: "Leite e derivados", kcal: 0, proteina: 0, carboidrato: 0, gordura: 0 },
  { nome: "Iogurte, sabor morango", categoria: "Leite e derivados", kcal: 70, proteina: 2.7, carboidrato: 9.7, gordura: 2.3 },
  { nome: "Iogurte, sabor pêssego", categoria: "Leite e derivados", kcal: 68, proteina: 2.5, carboidrato: 9.4, gordura: 2.3 },
  { nome: "Leite, condensado", categoria: "Leite e derivados", kcal: 313, proteina: 7.7, carboidrato: 57, gordura: 6.7 },
  { nome: "Leite, de cabra", categoria: "Leite e derivados", kcal: 66, proteina: 3.1, carboidrato: 5.2, gordura: 3.8 },
  { nome: "Leite, de vaca, achocolatado", categoria: "Leite e derivados", kcal: 83, proteina: 2.1, carboidrato: 14.2, gordura: 2.2 },
  { nome: "Leite, de vaca, desnatado, pó", categoria: "Leite e derivados", kcal: 362, proteina: 34.7, carboidrato: 53, gordura: 0.9 },
  { nome: "Leite, de vaca, desnatado, UHT", categoria: "Leite e derivados", kcal: 0, proteina: 0, carboidrato: 0, gordura: 0 },
  { nome: "Leite, de vaca, integral", categoria: "Leite e derivados", kcal: 0, proteina: 0, carboidrato: 0, gordura: 0 },
  { nome: "Leite, de vaca, integral, pó", categoria: "Leite e derivados", kcal: 497, proteina: 25.4, carboidrato: 39.2, gordura: 26.9 },
  { nome: "Leite, fermentado", categoria: "Leite e derivados", kcal: 70, proteina: 1.9, carboidrato: 15.7, gordura: 0.1 },
  { nome: "Queijo, minas, frescal", categoria: "Leite e derivados", kcal: 264, proteina: 17.4, carboidrato: 3.2, gordura: 20.2 },
  { nome: "Queijo, minas, meia cura", categoria: "Leite e derivados", kcal: 321, proteina: 21.2, carboidrato: 3.6, gordura: 24.6 },
  { nome: "Queijo, mozarela", categoria: "Leite e derivados", kcal: 330, proteina: 22.6, carboidrato: 3, gordura: 25.2 },
  { nome: "Queijo, parmesão", categoria: "Leite e derivados", kcal: 453, proteina: 35.6, carboidrato: 1.7, gordura: 33.5 },
  { nome: "Queijo, pasteurizado", categoria: "Leite e derivados", kcal: 303, proteina: 9.4, carboidrato: 5.7, gordura: 27.4 },
  { nome: "Queijo, petit suisse, morango", categoria: "Leite e derivados", kcal: 121, proteina: 5.8, carboidrato: 18.5, gordura: 2.8 },
  { nome: "Queijo, prato", categoria: "Leite e derivados", kcal: 360, proteina: 22.7, carboidrato: 1.9, gordura: 29.1 },
  { nome: "Queijo, requeijão, cremoso", categoria: "Leite e derivados", kcal: 257, proteina: 9.6, carboidrato: 2.4, gordura: 23.4 },
  { nome: "Queijo, ricota", categoria: "Leite e derivados", kcal: 140, proteina: 12.6, carboidrato: 3.8, gordura: 8.1 },
  { nome: "Bebida isotônica, sabores variados", categoria: "Bebidas (alcoólicas e não alcoólicas)", kcal: 26, proteina: 0, carboidrato: 6.4, gordura: 0 },
  { nome: "Café, infusão 10%", categoria: "Bebidas (alcoólicas e não alcoólicas)", kcal: 9, proteina: 0.7, carboidrato: 1.5, gordura: 0.1 },
  { nome: "Cana, aguardente 1", categoria: "Bebidas (alcoólicas e não alcoólicas)", kcal: 216, proteina: 0, carboidrato: 0, gordura: 0 },
  { nome: "Cana, caldo de", categoria: "Bebidas (alcoólicas e não alcoólicas)", kcal: 65, proteina: 0, carboidrato: 18.2, gordura: 0 },
  { nome: "Cerveja, pilsen 2", categoria: "Bebidas (alcoólicas e não alcoólicas)", kcal: 41, proteina: 0.6, carboidrato: 3.3, gordura: 0 },
  { nome: "Chá, erva-doce, infusão 5%", categoria: "Bebidas (alcoólicas e não alcoólicas)", kcal: 1, proteina: 0, carboidrato: 0.4, gordura: 0 },
  { nome: "Chá, mate, infusão 5%", categoria: "Bebidas (alcoólicas e não alcoólicas)", kcal: 3, proteina: 0, carboidrato: 0.6, gordura: 0.1 },
  { nome: "Chá, preto, infusão 5%", categoria: "Bebidas (alcoólicas e não alcoólicas)", kcal: 2, proteina: 0, carboidrato: 0.6, gordura: 0 },
  { nome: "Coco, água de", categoria: "Bebidas (alcoólicas e não alcoólicas)", kcal: 22, proteina: 0, carboidrato: 5.3, gordura: 0 },
  { nome: "Refrigerante, tipo água tônica", categoria: "Bebidas (alcoólicas e não alcoólicas)", kcal: 31, proteina: 0, carboidrato: 8, gordura: 0 },
  { nome: "Refrigerante, tipo cola", categoria: "Bebidas (alcoólicas e não alcoólicas)", kcal: 34, proteina: 0, carboidrato: 8.7, gordura: 0 },
  { nome: "Refrigerante, tipo guaraná", categoria: "Bebidas (alcoólicas e não alcoólicas)", kcal: 39, proteina: 0, carboidrato: 10, gordura: 0 },
  { nome: "Refrigerante, tipo laranja", categoria: "Bebidas (alcoólicas e não alcoólicas)", kcal: 46, proteina: 0, carboidrato: 11.8, gordura: 0 },
  { nome: "Refrigerante, tipo limão", categoria: "Bebidas (alcoólicas e não alcoólicas)", kcal: 40, proteina: 0, carboidrato: 10.3, gordura: 0 },
  { nome: "Omelete, de queijo", categoria: "Ovos e derivados", kcal: 268, proteina: 15.6, carboidrato: 0.4, gordura: 22 },
  { nome: "Ovo, de codorna, inteiro, cru", categoria: "Ovos e derivados", kcal: 177, proteina: 13.7, carboidrato: 0.8, gordura: 12.7 },
  { nome: "Ovo, de galinha, clara, cozida/10minutos", categoria: "Ovos e derivados", kcal: 59, proteina: 13.4, carboidrato: 0, gordura: 0.1 },
  { nome: "Ovo, de galinha, gema, cozida/10minutos", categoria: "Ovos e derivados", kcal: 353, proteina: 15.9, carboidrato: 1.6, gordura: 30.8 },
  { nome: "Ovo, de galinha, inteiro, cozido/10minutos", categoria: "Ovos e derivados", kcal: 146, proteina: 13.3, carboidrato: 0.6, gordura: 9.5 },
  { nome: "Ovo, de galinha, inteiro, cru", categoria: "Ovos e derivados", kcal: 143, proteina: 13, carboidrato: 1.6, gordura: 8.9 },
  { nome: "Ovo, de galinha, inteiro, frito", categoria: "Ovos e derivados", kcal: 240, proteina: 15.6, carboidrato: 1.2, gordura: 18.6 },
  { nome: "Achocolatado, pó", categoria: "Produtos açucarados", kcal: 401, proteina: 4.2, carboidrato: 91.2, gordura: 2.2 },
  { nome: "Açúcar, cristal", categoria: "Produtos açucarados", kcal: 387, proteina: 0.3, carboidrato: 99.6, gordura: 0 },
  { nome: "Açúcar, mascavo", categoria: "Produtos açucarados", kcal: 369, proteina: 0.8, carboidrato: 94.5, gordura: 0.1 },
  { nome: "Açúcar, refinado", categoria: "Produtos açucarados", kcal: 387, proteina: 0.3, carboidrato: 99.5, gordura: 0 },
  { nome: "Chocolate, ao leite", categoria: "Produtos açucarados", kcal: 540, proteina: 7.2, carboidrato: 59.6, gordura: 30.3 },
  { nome: "Chocolate, ao leite, com castanha do Pará", categoria: "Produtos açucarados", kcal: 559, proteina: 7.4, carboidrato: 55.4, gordura: 34.2 },
  { nome: "Chocolate, ao leite, dietético", categoria: "Produtos açucarados", kcal: 557, proteina: 6.9, carboidrato: 56.3, gordura: 33.8 },
  { nome: "Chocolate, meio amargo", categoria: "Produtos açucarados", kcal: 475, proteina: 4.9, carboidrato: 62.4, gordura: 29.9 },
  { nome: "Cocada branca", categoria: "Produtos açucarados", kcal: 449, proteina: 1.1, carboidrato: 81.4, gordura: 13.6 },
  { nome: "Doce, de abóbora, cremoso", categoria: "Produtos açucarados", kcal: 199, proteina: 0.9, carboidrato: 54.6, gordura: 0.2 },
  { nome: "Doce, de leite, cremoso", categoria: "Produtos açucarados", kcal: 306, proteina: 5.5, carboidrato: 59.5, gordura: 6 },
  { nome: "Geléia, mocotó, natural", categoria: "Produtos açucarados", kcal: 106, proteina: 2.1, carboidrato: 24.2, gordura: 0.1 },
  { nome: "Glicose de milho", categoria: "Produtos açucarados", kcal: 292, proteina: 0, carboidrato: 79.4, gordura: 0 },
  { nome: "Maria mole", categoria: "Produtos açucarados", kcal: 301, proteina: 3.8, carboidrato: 73.6, gordura: 0.2 },
  { nome: "Maria mole, coco queimado", categoria: "Produtos açucarados", kcal: 307, proteina: 3.9, carboidrato: 75.1, gordura: 0.1 },
  { nome: "Marmelada", categoria: "Produtos açucarados", kcal: 257, proteina: 0.4, carboidrato: 70.8, gordura: 0.1 },
  { nome: "Mel, de abelha", categoria: "Produtos açucarados", kcal: 309, proteina: 0, carboidrato: 84, gordura: 0 },
  { nome: "Melado", categoria: "Produtos açucarados", kcal: 297, proteina: 0, carboidrato: 76.6, gordura: 0 },
  { nome: "Quindim", categoria: "Produtos açucarados", kcal: 411, proteina: 4.7, carboidrato: 46.3, gordura: 24.4 },
  { nome: "Rapadura", categoria: "Produtos açucarados", kcal: 352, proteina: 1, carboidrato: 90.8, gordura: 0.1 },
  { nome: "Café, pó, torrado", categoria: "Miscelâneas", kcal: 419, proteina: 14.7, carboidrato: 65.8, gordura: 11.9 },
  { nome: "Capuccino, pó", categoria: "Miscelâneas", kcal: 417, proteina: 11.3, carboidrato: 73.6, gordura: 8.6 },
  { nome: "Fermento em pó, químico", categoria: "Miscelâneas", kcal: 90, proteina: 0.5, carboidrato: 43.9, gordura: 0.1 },
  { nome: "Fermento, biológico, levedura, tablete", categoria: "Miscelâneas", kcal: 90, proteina: 17, carboidrato: 7.7, gordura: 1.5 },
  { nome: "Gelatina, sabores variados, pó", categoria: "Miscelâneas", kcal: 380, proteina: 8.9, carboidrato: 89.2, gordura: 0 },
  { nome: "Sal, dietético", categoria: "Miscelâneas", kcal: 0, proteina: 0, carboidrato: 0, gordura: 0 },
  { nome: "Sal, grosso", categoria: "Miscelâneas", kcal: 0, proteina: 0, carboidrato: 0, gordura: 0 },
  { nome: "Shoyu", categoria: "Miscelâneas", kcal: 61, proteina: 3.3, carboidrato: 11.6, gordura: 0.3 },
  { nome: "Tempero a base de sal", categoria: "Miscelâneas", kcal: 21, proteina: 2.7, carboidrato: 2.1, gordura: 0.3 },
  { nome: "Azeitona, preta, conserva", categoria: "Outros alimentos industrializados", kcal: 194, proteina: 1.2, carboidrato: 5.5, gordura: 20.3 },
  { nome: "Azeitona, verde, conserva", categoria: "Outros alimentos industrializados", kcal: 137, proteina: 0.9, carboidrato: 4.1, gordura: 14.2 },
  { nome: "Chantilly, spray, com gordura vegetal", categoria: "Outros alimentos industrializados", kcal: 315, proteina: 0.5, carboidrato: 16.9, gordura: 27.3 },
  { nome: "Leite, de coco", categoria: "Outros alimentos industrializados", kcal: 166, proteina: 1, carboidrato: 2.2, gordura: 18.4 },
  { nome: "Maionese, tradicional com ovos", categoria: "Outros alimentos industrializados", kcal: 302, proteina: 0.6, carboidrato: 7.9, gordura: 30.5 },
  { nome: "Acarajé", categoria: "Alimentos preparados", kcal: 289, proteina: 8.3, carboidrato: 19.1, gordura: 19.9 },
  { nome: "Arroz carreteiro", categoria: "Alimentos preparados", kcal: 154, proteina: 10.8, carboidrato: 11.6, gordura: 7.1 },
  { nome: "Baião de dois, arroz e feijão-de-corda", categoria: "Alimentos preparados", kcal: 136, proteina: 6.2, carboidrato: 20.4, gordura: 3.2 },
  { nome: "Barreado", categoria: "Alimentos preparados", kcal: 165, proteina: 18.3, carboidrato: 0.2, gordura: 9.5 },
  { nome: "Bife à cavalo, com contra filé", categoria: "Alimentos preparados", kcal: 291, proteina: 23.7, carboidrato: 0, gordura: 21.1 },
  { nome: "Bolinho de arroz", categoria: "Alimentos preparados", kcal: 274, proteina: 8, carboidrato: 41.7, gordura: 8.3 },
  { nome: "Camarão à baiana", categoria: "Alimentos preparados", kcal: 101, proteina: 7.9, carboidrato: 3.2, gordura: 6 },
  { nome: "Charuto, de repolho", categoria: "Alimentos preparados", kcal: 78, proteina: 6.8, carboidrato: 10.1, gordura: 1.1 },
  { nome: "Cuscuz, de milho, cozido com sal", categoria: "Alimentos preparados", kcal: 113, proteina: 2.2, carboidrato: 25.3, gordura: 0.7 },
  { nome: "Cuscuz, paulista", categoria: "Alimentos preparados", kcal: 142, proteina: 2.6, carboidrato: 22.5, gordura: 4.6 },
  { nome: "Cuxá, molho", categoria: "Alimentos preparados", kcal: 80, proteina: 5.6, carboidrato: 5.7, gordura: 3.6 },
  { nome: "Dobradinha", categoria: "Alimentos preparados", kcal: 125, proteina: 19.8, carboidrato: 0, gordura: 4.4 },
  { nome: "Estrogonofe de carne", categoria: "Alimentos preparados", kcal: 173, proteina: 15, carboidrato: 3, gordura: 10.8 },
  { nome: "Estrogonofe de frango", categoria: "Alimentos preparados", kcal: 157, proteina: 17.6, carboidrato: 2.6, gordura: 8 },
  { nome: "Feijão tropeiro mineiro", categoria: "Alimentos preparados", kcal: 152, proteina: 10.2, carboidrato: 19.6, gordura: 6.8 },
  { nome: "Feijoada", categoria: "Alimentos preparados", kcal: 117, proteina: 8.7, carboidrato: 11.6, gordura: 6.5 },
  { nome: "Frango, com açafrão", categoria: "Alimentos preparados", kcal: 113, proteina: 9.7, carboidrato: 4.1, gordura: 6.2 },
  { nome: "Macarrão, molho bolognesa", categoria: "Alimentos preparados", kcal: 120, proteina: 4.9, carboidrato: 22.5, gordura: 0.9 },
  { nome: "Maniçoba", categoria: "Alimentos preparados", kcal: 134, proteina: 10, carboidrato: 3.4, gordura: 8.7 },
  { nome: "Quibebe", categoria: "Alimentos preparados", kcal: 86, proteina: 8.6, carboidrato: 6.6, gordura: 2.7 },
  { nome: "Salada, de legumes, com maionese", categoria: "Alimentos preparados", kcal: 96, proteina: 1.1, carboidrato: 8.9, gordura: 7 },
  { nome: "Salada, de legumes, cozida no vapor", categoria: "Alimentos preparados", kcal: 35, proteina: 2, carboidrato: 7.1, gordura: 0.3 },
  { nome: "Salpicão, de frango", categoria: "Alimentos preparados", kcal: 148, proteina: 13.9, carboidrato: 4.6, gordura: 7.8 },
  { nome: "Sarapatel", categoria: "Alimentos preparados", kcal: 123, proteina: 18.5, carboidrato: 1.1, gordura: 4.4 },
  { nome: "Tabule", categoria: "Alimentos preparados", kcal: 57, proteina: 2, carboidrato: 10.6, gordura: 1.2 },
  { nome: "Tacacá", categoria: "Alimentos preparados", kcal: 47, proteina: 7, carboidrato: 3.4, gordura: 0.4 },
  { nome: "Tapioca, com manteiga", categoria: "Alimentos preparados", kcal: 348, proteina: 0.1, carboidrato: 63.6, gordura: 10.9 },
  { nome: "Tucupi, com pimenta-de-cheiro", categoria: "Alimentos preparados", kcal: 27, proteina: 2.1, carboidrato: 4.7, gordura: 0.3 },
  { nome: "Vaca atolada", categoria: "Alimentos preparados", kcal: 145, proteina: 5.1, carboidrato: 10.1, gordura: 9.3 },
  { nome: "Vatapá", categoria: "Alimentos preparados", kcal: 255, proteina: 6, carboidrato: 9.7, gordura: 23.2 },
  { nome: "Virado à paulista", categoria: "Alimentos preparados", kcal: 307, proteina: 10.2, carboidrato: 14.1, gordura: 25.6 },
  { nome: "Yakisoba", categoria: "Alimentos preparados", kcal: 113, proteina: 7.5, carboidrato: 18.3, gordura: 2.6 },
  { nome: "Amendoim, grão, cru", categoria: "Leguminosas e derivados", kcal: 544, proteina: 27.2, carboidrato: 20.3, gordura: 43.9 },
  { nome: "Amendoim, torrado, salgado", categoria: "Leguminosas e derivados", kcal: 606, proteina: 22.5, carboidrato: 18.7, gordura: 54 },
  { nome: "Ervilha, em vagem", categoria: "Leguminosas e derivados", kcal: 88, proteina: 7.5, carboidrato: 14.2, gordura: 0.5 },
  { nome: "Ervilha, enlatada, drenada", categoria: "Leguminosas e derivados", kcal: 74, proteina: 4.6, carboidrato: 13.4, gordura: 0.4 },
  { nome: "Feijão, carioca, cozido", categoria: "Leguminosas e derivados", kcal: 76, proteina: 4.8, carboidrato: 13.6, gordura: 0.5 },
  { nome: "Feijão, carioca, cru", categoria: "Leguminosas e derivados", kcal: 329, proteina: 20, carboidrato: 61.2, gordura: 1.3 },
  { nome: "Feijão, fradinho, cozido", categoria: "Leguminosas e derivados", kcal: 78, proteina: 5.1, carboidrato: 13.5, gordura: 0.6 },
  { nome: "Feijão, fradinho, cru", categoria: "Leguminosas e derivados", kcal: 339, proteina: 20.2, carboidrato: 61.2, gordura: 2.4 },
  { nome: "Feijão, jalo, cozido", categoria: "Leguminosas e derivados", kcal: 93, proteina: 6.1, carboidrato: 16.5, gordura: 0.5 },
  { nome: "Feijão, jalo, cru", categoria: "Leguminosas e derivados", kcal: 328, proteina: 20.1, carboidrato: 61.5, gordura: 0.9 },
  { nome: "Feijão, preto, cozido", categoria: "Leguminosas e derivados", kcal: 77, proteina: 4.5, carboidrato: 14, gordura: 0.5 },
  { nome: "Feijão, preto, cru", categoria: "Leguminosas e derivados", kcal: 324, proteina: 21.3, carboidrato: 58.8, gordura: 1.2 },
  { nome: "Feijão, rajado, cozido", categoria: "Leguminosas e derivados", kcal: 85, proteina: 5.5, carboidrato: 15.3, gordura: 0.4 },
  { nome: "Feijão, rajado, cru", categoria: "Leguminosas e derivados", kcal: 326, proteina: 17.3, carboidrato: 62.9, gordura: 1.2 },
  { nome: "Feijão, rosinha, cozido", categoria: "Leguminosas e derivados", kcal: 68, proteina: 4.5, carboidrato: 11.8, gordura: 0.5 },
  { nome: "Feijão, rosinha, cru", categoria: "Leguminosas e derivados", kcal: 337, proteina: 20.9, carboidrato: 62.2, gordura: 1.3 },
  { nome: "Feijão, roxo, cozido", categoria: "Leguminosas e derivados", kcal: 77, proteina: 5.7, carboidrato: 12.9, gordura: 0.5 },
  { nome: "Feijão, roxo, cru", categoria: "Leguminosas e derivados", kcal: 331, proteina: 22.2, carboidrato: 60, gordura: 1.2 },
  { nome: "Grão-de-bico, cru", categoria: "Leguminosas e derivados", kcal: 355, proteina: 21.2, carboidrato: 57.9, gordura: 5.4 },
  { nome: "Guandu, cru", categoria: "Leguminosas e derivados", kcal: 344, proteina: 19, carboidrato: 64, gordura: 2.1 },
  { nome: "Lentilha, cozida", categoria: "Leguminosas e derivados", kcal: 93, proteina: 6.3, carboidrato: 16.3, gordura: 0.5 },
  { nome: "Lentilha, crua", categoria: "Leguminosas e derivados", kcal: 339, proteina: 23.2, carboidrato: 62, gordura: 0.8 },
  { nome: "Paçoca, amendoim", categoria: "Leguminosas e derivados", kcal: 487, proteina: 16, carboidrato: 52.4, gordura: 26.1 },
  { nome: "Pé-de-moleque, amendoim", categoria: "Leguminosas e derivados", kcal: 503, proteina: 13.2, carboidrato: 54.7, gordura: 28 },
  { nome: "Soja, farinha", categoria: "Leguminosas e derivados", kcal: 404, proteina: 36, carboidrato: 38.4, gordura: 14.6 },
  { nome: "Soja, extrato solúvel, natural, fluido", categoria: "Leguminosas e derivados", kcal: 39, proteina: 2.4, carboidrato: 4.3, gordura: 1.6 },
  { nome: "Soja, extrato solúvel, pó", categoria: "Leguminosas e derivados", kcal: 459, proteina: 35.7, carboidrato: 28.5, gordura: 26.2 },
  { nome: "Soja, queijo (tofu)", categoria: "Leguminosas e derivados", kcal: 64, proteina: 6.6, carboidrato: 2.1, gordura: 4 },
  { nome: "Tremoço, cru", categoria: "Leguminosas e derivados", kcal: 381, proteina: 33.6, carboidrato: 43.8, gordura: 10.3 },
  { nome: "Tremoço, em conserva", categoria: "Leguminosas e derivados", kcal: 121, proteina: 11.1, carboidrato: 12.4, gordura: 3.8 },
  { nome: "Amêndoa, torrada, salgada", categoria: "Nozes e sementes", kcal: 581, proteina: 18.6, carboidrato: 29.5, gordura: 47.3 },
  { nome: "Castanha-de-caju, torrada, salgada", categoria: "Nozes e sementes", kcal: 570, proteina: 18.5, carboidrato: 29.1, gordura: 46.3 },
  { nome: "Castanha-do-Brasil, crua", categoria: "Nozes e sementes", kcal: 643, proteina: 14.5, carboidrato: 15.1, gordura: 63.5 },
  { nome: "Coco, cru", categoria: "Nozes e sementes", kcal: 406, proteina: 3.7, carboidrato: 10.4, gordura: 42 },
  { nome: "Coco,  verde, cru", categoria: "Nozes e sementes", kcal: 0, proteina: 0, carboidrato: 0, gordura: 0 },
  { nome: "Farinha, de mesocarpo de babaçu, crua", categoria: "Nozes e sementes", kcal: 329, proteina: 1.4, carboidrato: 79.2, gordura: 0.2 },
  { nome: "Gergelim, semente", categoria: "Nozes e sementes", kcal: 584, proteina: 21.2, carboidrato: 21.6, gordura: 50.4 },
  { nome: "Linhaça, semente", categoria: "Nozes e sementes", kcal: 495, proteina: 14.1, carboidrato: 43.3, gordura: 32.3 },
  { nome: "Pinhão, cozido", categoria: "Nozes e sementes", kcal: 174, proteina: 3, carboidrato: 43.9, gordura: 0.7 },
  { nome: "Pupunha, cozida", categoria: "Nozes e sementes", kcal: 219, proteina: 2.5, carboidrato: 29.6, gordura: 12.8 },
  { nome: "Noz, crua", categoria: "Nozes e sementes", kcal: 620, proteina: 14, carboidrato: 18.4, gordura: 59.4 },
];
